### ISSUE TITLE
what do i do with the codes from discord??

### ISSUE THREAD

**Issue by IlikeFreerunning** [JonnyBro/beatrun#100]
what do i do with the codes from discord??

**Comment by JonnyBro** [comment]
Next time please ask questions on our Discord server, this is for bug reports.
[Discord channel with info](https://discord.com/channels/1113394230002454560/1113443771569418270)
[Courses database](https://courses.beatrun.ru)

**Comment by IlikeFreerunning** [comment]
k sorry il remember that next time
