### ISSUE TITLE
[Suggestion] Space Bar to climb

### ISSUE THREAD

**Issue by CootieDwagon** [JonnyBro/beatrun#102]
I don't know if it would be possible. but I'm wondering if you could have it so when we are hanging on a ledge that we can press "space bar" to climb up instead of pressing W? or perhaps have a toggle we can swap between space bar and W?

i don't know if having it as space bar would interfere with anything. so I'm just wondering

**Comment by JonnyBro** [comment]
completely forgot about this issue. Added this some time ago, so just update your beatrun and you can climb up with W **or** Space
