### ISSUE TITLE
[Bug] Instant death after Totsugeki

### ISSUE THREAD

**Issue by SleepyCatOfficial** [JonnyBro/beatrun#109]
Whenever i try to Totsugeki i instantly die because of the explosion, i don't have any mods that can change the explosion radius or even any mod that could mess up beatrun, the only mods that could mess up beatrun are disabled, please help!

https://github.com/JonnyBro/beatrun/assets/144239890/6c01744b-33ef-47ce-b2ea-e236194c5b05

**Comment by JonnyBro** [comment]
code didn't changed since october and no one ever reported that. Disable all your addons and try again

**Comment by SleepyCatOfficial** [comment]
> code didn't changed since october and no one ever reported that. Disable all your addons and try again

alr, will try that

**Comment by SleepyCatOfficial** [comment]
ok wtf now it works

**Comment by SleepyCatOfficial** [comment]
i have uninstalled the two mods that could have made that happen and it's still happening

**Comment by SleepyCatOfficial** [comment]
Now it's damaging me and occasionally killing me, but with every mod disabled it's fine, i wanna play with mods on (except the ones that beatrun says you shouldn't play with), so essentially, i'm kinda stuck here lol

**Comment by JonnyBro** [comment]
moved to discord
