### ISSUE TITLE
[Bug] Black Boxes In Build Mode Props

### ISSUE THREAD

**Issue by CootieDwagon** [JonnyBro/beatrun#111]
**Describe the bug**
when entering build mode and looking at the "props" section, if you scroll down there are a LOT of black squares

**To Reproduce**
1. into build mode
2. scroll down to see black squares

**Expected behavior**
i expected to not see blac ksquares

![bug](https://github.com/JonnyBro/beatrun/assets/84007270/e07ec126-c4e7-4687-ae52-1575ad95e7ee)

**Additional information:**
 - Game Version: chromium, x64
- Game Type: singleplayer

**Additional context**
Maybe addons list or settings you changed in Beatrun's config menu.

**Comment by JonnyBro** [comment]
can you try non beta version of the game?

**Comment by JonnyBro** [comment]
also, do you have CS;S and HL2 (and episodes) mounted?

**Comment by CootieDwagon** [comment]
ill try the none beta version and yes i do have CS:S and HL2. as well as HL2:EP 1/2 mounted

**Comment by CootieDwagon** [comment]
tried the normal version AKA none beta. still has the "black boxes" issue. ill try installing the update that you posted 19h ago at the time of this reply

**Comment by CootieDwagon** [comment]
ok, being in "none beta" fixed "some" of the black boxes. but i still have a LOT more. for testing purpose, im gonna re-install gmod and then ONLY have Beatrun installed to test this

**Comment by CootieDwagon** [comment]
yeah, did a fresh install of Gmod. none beta branch. made sure i had CS:S and all the HL2 stuff mounted and installed. but im still getting black boxes. i was able to load in "some" of the black boxes via opening the spawn menu and finding the prop. from what im seeing it seems like Beatrun isn't properly loading in the "thumbnails" and in order to do so i would have to manually load them in by manually searching for each prop in the spawn menu and that would take so damn long that i do not want to do that

**Comment by JonnyBro** [comment]
those changes were reverted in favor of other way of placing props in courses, check our Discord, there will be news soon!
