### ISSUE TITLE
[Suggestion] A downloads section

### ISSUE THREAD

**Issue by Mememan97GithubEdition** [JonnyBro/beatrun#113]
**Is your feature request related to a problem? Please describe.**

A download section so I don't need to download everything else

**Describe the solution you'd like**

A simple downloads section to make downloading the mod easier

**Describe alternatives you've considered**

**Additional context**
A simple downloads section so that people can directly download the addon

**Comment by JonnyBro** [comment]
Have you tried those?
![image](https://github.com/JonnyBro/beatrun/assets/48434875/0a387d29-a72a-459d-bb1f-e584fa1cf745)
![image](https://github.com/JonnyBro/beatrun/assets/48434875/8daecc27-4a3c-488a-ad33-bf1dda498fd5)

**Comment by Mememan97GithubEdition** [comment]
I meant something like this:
![downloads](https://github.com/JonnyBro/beatrun/assets/149274477/5345508d-3284-4e16-a665-9fbcf61a9f92)

**Comment by Mememan97GithubEdition** [comment]
Understood.
