### ISSUE TITLE
I'm In The Ground

### ISSUE THREAD

**Issue by VaeAstra** [JonnyBro/beatrun#115]
I've done everything I could. I disabled the addons that conflict, uninstalled dynamic height, and uninstalled the majority of my vmanip and other movement related mods, yet I'm still in the ground like this. Am I doing something wrong here?
![20231109232330_1](https://github.com/JonnyBro/beatrun/assets/106640728/3dafb382-df27-4103-bc5f-16cb41a0d45c)

**Comment by JonnyBro** [comment]
update you beatrun, disable ALL addons, restart the game and try again. If this fixes it, enable every addon one by one and let me know if you will find a conflicting addon.

**Comment by VaeAstra** [comment]
Just decided to nuke it all and start fresh. To be honest, I had way to many addons for my own good and needed a good change of pace away from tactical realism and stuff. It's all fine now, but I will say that Enhanced Playermodel Selector doesn't work in Beatrun.

**Comment by JonnyBro** [comment]
> Enhanced Playermodel Selector doesn't work in Beatrun.
¯\\_(ツ)_/¯, but [this](https://steamcommunity.com/sharedfiles/filedetails/?id=2257795841) works fine and allows to change hands independed from the model.
