### ISSUE TITLE
courses?

### ISSUE THREAD

**Issue by IlikeFreerunning** [JonnyBro/beatrun#116]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by IlikeFreerunning** [comment]
sorry accidenaly pressed enter

**Comment by IlikeFreerunning** [comment]
how do I enter community made courses on beatrun.ru?

**Comment by JonnyBro** [comment]
Please ask those questions on Discord, stop creating Issues here
https://courses.beatrun.ru
https://discord.com/channels/1113394230002454560/1113443771569418270
