### ISSUE TITLE
ledge climbing 

### ISSUE THREAD

**Issue by IlikeFreerunning** [JonnyBro/beatrun#117]
when you see a ledge or anywhere you can climb or even climb/vault can you make a button so instead of fully climbing over it you climb to hold the ledge and then press w or spacebar to climb? ps: i know you can release w to hold on the the ledge but on shorter obstacles its every unreliable.

**Comment by JonnyBro** [comment]
no

**Comment by IlikeFreerunning** [comment]
dam

**Comment by IlikeFreerunning** [comment]
pretty please?
