### ISSUE TITLE
can you make it so whenever you stand in front of a wall your hands touch it

### ISSUE THREAD

**Issue by IlikeFreerunning** [JonnyBro/beatrun#119]
can you make it so whenever you stand in front of a wall your hands touch it?

**Comment by JonnyBro** [comment]
we had this, but my implementation is ass so i removed it for now

**Comment by IlikeFreerunning** [comment]
ohhh do you know if this will come in a later update?

**Comment by JonnyBro** [comment]
maybe

**Comment by IlikeFreerunning** [comment]
ty
