### ISSUE TITLE
quickturn in air bug

### ISSUE THREAD

**Issue by Wenninc** [JonnyBro/beatrun#12]
Hi, thank you for the beatrun. So i have this bug, vmaniprework is installed(workshop version i deleted) Everything is working except this

https://github.com/JonnyBro/beatrun/assets/135866726/d5f3e27c-24f5-4e93-8f02-c00b0cace14d

**Comment by jeffthekillerz** [comment]
cant replicate. what did you do beforehand?

**Comment by Wenninc** [comment]
i think this was bug of the map, because after that i was playing on different map and i dont have that bug

**Comment by Wenninc** [comment]
btw map name is edge runner
