### ISSUE TITLE
[Bug] Stuck when climbing/mantling 

### ISSUE THREAD

**Issue by chanxteck** [JonnyBro/beatrun#129]
**Describe the bug**
infinitely floating/stuck when climbing/mantling an object

**To Reproduce**
1. grab a ledge so your body theoretically clips though the ground
4. See video posted, this happens frequently, another example not shown are the barrels on another tf2 map but this has happened on non-tf2 maps

**Expected behavior**
simply letting go

**Screenshots/Videos**
https://streamable.com/dg4h1i

**Additional information:**
 - Game Version: latest
- Game Type: freeplay

**Additional context**
only thing ive done in beatrun is increasing max speed by 2/3kph

**Comment by 1nfameArts** [comment]
your body is stuck in the ground, the game has to teleport you out but it doesn't
source games treat being clipped underground (even abit) as unable to move, so this is logical that this happens
needs to add a line in the climbing/mantling code to, if not moved in 5 seconds (or less), teleport you up (if there is an available space).
