### ISSUE TITLE
[Suggestion] Allow the player to grab overhangs (video included)

### ISSUE THREAD

**Issue by chanxteck** [JonnyBro/beatrun#130]
Anytime there is a slight/moderate overhang its impossible to fully vertically scale the wall/mantle onto the overhang. this happens extremely frequently when freerunning random maps (maps that aren't made to be parkoured on are the most fun as you have to create all the setups and routing yourself)

The fix:
either automatic or a manual way to mantle onto short to moderate overhangs by slightly back kicking off the wall enough to gain height while also allowing your arms to extend to mantle or by auto grabbing the ledge whichever is easier but a more manual way to grab overhangs would be far more fun way to play.

Alternative fix:
allow the player to rapidly 180 degree RMB twice to kick off and then turn around and grab overhang

Here's a video of the issue and what the suggestion would fix: https://clipchamp.com/watch/VsEOF21Hx4y

**Comment by IlikeFreerunning** [comment]
BRO WE NEED THIS
