### ISSUE TITLE
[Bug] common issue with MWB

### ISSUE THREAD

**Issue by dataesucsdeek** [JonnyBro/beatrun#133]
certain vmanip things. ONLY when using beatrun. do NOT work with mwbase
(when ever i disabled beatrun they worked. so im putting the bug report here)
example. https://steamcommunity.com/sharedfiles/filedetails/?id=3100506899&searchtext=
when ever i hold the button to hold out the scanner. my left hand doesnt move off the gun. (WITH BEATRUN)
but WITHOUT BEATRUN it works perfectly fine. could this be fixed?

**Comment by dataesucsdeek** [comment]
a nother thing is quicknade. that also doesnt work

**Comment by JonnyBro** [comment]
VManip is not compatible with beatrun, beatrun removes all of the vmanip things

**Comment by dataesucsdeek** [comment]
vmanip IS compatible. but in certain cases its selectively breaking itself. ONLY mwbase has this issue.
for me atleast.

**Comment by dataesucsdeek** [comment]
from my experience. it only bugs out if you use vmanip parkour addons.
not quicknade/alien isolation scanner.

**Comment by dataesucsdeek** [comment]
https://media.discordapp.net/attachments/964831725668683826/1180206450350506045/gmod_61kmkSGIXL.png?ex=657c93e8&is=656a1ee8&hm=4ec56942e0f07df544ffcbffc05785f91c797a117cee726ab0e41b8fb5569df8&=&format=webp&quality=lossless&width=1060&height=663

https://media.discordapp.net/attachments/964831725668683826/1180206403965694022/gmod_xFOQ08pdjK.png?ex=657c93dd&is=656a1edd&hm=347015c76a4f00ba358faea25622ec40fd7e366d558501173896f8740d0959d4&=&format=webp&quality=lossless&width=1060&height=663

**Comment by dataesucsdeek** [comment]
screenshot proof

**Comment by dataesucsdeek** [comment]
this is exactly why i asked if you could take a look at whats causing this issue with vmanip and MWB while beatrun is active

**Comment by dataesucsdeek** [comment]
theres 2 screenshots above.
the first ones arc9. 2nd ones mwb. 
beatrun does NOT cancel out the vmanip anims.
(freeplay watermark at bottom left so you cant say im bullshitting you.)

**Comment by dataesucsdeek** [comment]
> https://media.discordapp.net/attachments/964831725668683826/1180206450350506045/gmod_61kmkSGIXL.png?ex=657c93e8&is=656a1ee8&hm=4ec56942e0f07df544ffcbffc05785f91c797a117cee726ab0e41b8fb5569df8&=&format=webp&quality=lossless&width=1060&height=663
> 
> https://media.discordapp.net/attachments/964831725668683826/1180206403965694022/gmod_xFOQ08pdjK.png?ex=657c93dd&is=656a1edd&hm=347015c76a4f00ba358faea25622ec40fd7e366d558501173896f8740d0959d4&=&format=webp&quality=lossless&width=1060&height=663

*nudge nudge*
