### ISSUE TITLE
[Suggestion] Some suggestions

### ISSUE THREAD

**Issue by LeJuanKM** [JonnyBro/beatrun#136]
1#
The current idle standing is pretty hunched over, though it works really well, it looks a bit goofy. 

2#
Enabling the ladder climbing animation for EVERY ladder in the game would be amazing. I've tried doing it myself by looping through all ladder entities on a map and simply replacing them with br_ladder but that doesn't really work since they aren't all the same length and other issues.

3# 
This is really just an arcady/throwing it out there suggestion but a parachute compatible with beatrun 🤷

Great work yall are doing!

**Comment by JonnyBro** [comment]
1. Anims are made by MTB, they look how he wants but you can ask him if he wants to change them.
2. Pretty much impossible to calculate the height for every ladder on the map.
3. Just no.

**Comment by LeJuanKM** [comment]
Ah, I understand, thank you.
