### ISSUE TITLE
[Bug] if i roll i would slide and after the slide i get stuck (when i was trying to do roll i only press shift)

### ISSUE THREAD

**Issue by Ajuso007** [JonnyBro/beatrun#138]
https://github.com/JonnyBro/beatrun/assets/155564918/917665db-7882-4039-9856-ce527c621053

**Comment by JonnyBro** [comment]
update your beatrun, restart the game, unsub from some addons

**Comment by Epicthere654** [comment]
I am experiencing the same issue. I have updated beatrun, and have downloaded it multiple times. I have also uninstalled addons and it still won't work.

**Comment by Epicthere654** [comment]
I found out that the vr mod addon was causing the issue for me but idk if that is for everyone.
