### ISSUE TITLE
[Suggestion] How do I use the mod on sandbox mode

### ISSUE THREAD

**Issue by Lufims** [JonnyBro/beatrun#139]
**Is your feature request related to a problem? Please describe.**
I can't use the mod in sandbox, or i'm just an idiot that doesn't know how, but, is basically that, a way to use the mod on other gamemode like sandbox for example

**Describe the solution you'd like**
Use the mod on other gamemodes

**Describe alternatives you've considered**
I didn't consider any alternatives

**Additional context**
Basically what I said

**Comment by JonnyBro** [comment]
beatrun is the gamemode that is based on sandbox
