### ISSUE TITLE
runnerhands viewmodel clipping bug

### ISSUE THREAD

**Issue by mightbeusual** [JonnyBro/beatrun#14]
so there are certain chances on some maps that the runnerhands viewmodel would glitch out and clip with your view. the most notable one was on the map br_blitz. i've tried rechanging the beta build, but it doesn't seem to solve it. here is some footage

https://github.com/JonnyBro/beatrun/assets/135952698/fa6915ba-1be3-485b-9365-b42a1758ade2

**Comment by relaxtakenotes** [comment]
note for me or for someone else: this is related to frametime and viewmodel lag/lerp calculation

**Comment by JonnyBro** [comment]
How much fps you got on that map and course?

**Comment by mightbeusual** [comment]
i got around 60 fps.
