### ISSUE TITLE
[Suggestion] A way to use the mod in the half life campaign (1 and 2)

### ISSUE THREAD

**Issue by Lufims** [JonnyBro/beatrun#140]
**Is your feature request related to a problem? Please describe.**
I made other issue, but I didn't express myself correctly, but, is basically the title

**Describe the solution you'd like**
The title

**Describe alternatives you've considered**
I didn't consider

**Additional context**
The title

**Comment by JonnyBro** [comment]
Select beatrun gamemode and open HL2 map
