### ISSUE TITLE
I can't equip a weapon or spawn anything (Might be bug)

### ISSUE THREAD

**Issue by RedbunGaming** [JonnyBro/beatrun#141]
I can't spawn anything in or get weapons? im in single player and if it's not a bug can someone tell me how? also i did just install this so if this is a dumb question srry

NEVERMIND I FOUND OUT YOU TYPE SOMETHING IN CONSOLE THANK U

**Comment by CoolCode124** [comment]
But, how?

**Comment by JonnyBro** [comment]
Should be fixed by latest commit
