### ISSUE TITLE
[Bug] Broken Thirdperson Animations

### ISSUE THREAD

**Issue by RizzKingBrook** [JonnyBro/beatrun#142]
Animations are broken for me in thirdperson. Firstperson animations are fine. The issue still occurs when all addons are disabled. If I am able to disable my thirdperson animations then I don't mind too much if it is the fix. Please tell me how to disable thirdperson anims if so,
![Issue1](https://github.com/JonnyBro/beatrun/assets/130828860/45070ad5-1121-4f52-bbba-3dd8921f7388)
![Issue2](https://github.com/JonnyBro/beatrun/assets/130828860/6f72d187-e7e1-44ef-b893-6ff9bbdc45cb)

 - Game Version: chromium, x64]
- Game Type: singleplayer and multiplayer

**Comment by JonnyBro** [comment]
they are never ment to be in third person, beatrun is first person only
