### ISSUE TITLE
[Bug] Camera clipping through ground, and a contorted playermodel

### ISSUE THREAD

**Issue by reeeeenooooowhyyyy** [JonnyBro/beatrun#147]
**Describe the bug**
Upon spawning my camera clips through the ground and I have a contorted playermodel, I have disabled all conflicting addons beforehand so I don't know what's actually causing this

**To Reproduce**
It came like that first installed so I have no way of really helping with this

https://github.com/JonnyBro/beatrun/assets/69268656/6b2e00eb-79eb-4c9f-aac7-42145fdd3d6a

**Comment by LeJuanKM** [comment]
You have an addon that messes with the calcview most likely. I had the same issue. Anything that alters your first person view like some vmanip mods or something like the enhanced camera mod can break it. Try disabling all addons and check if you still get the error. If yes, verify installation. If no, start enabling addons until you find the one that causes it.

**Comment by JonnyBro** [comment]
disable all addons (vmanip too) and try again
