### ISSUE TITLE
[Bug] [Linux] Failed to load sounds from subfolders of "mirrorsedge/" folder.

### ISSUE THREAD

**Issue by Turelk** [JonnyBro/beatrun#148]
**Describe the bug**
Beatrun sounds that are in a subfolder of the "mirrorsedge" folder, it can't play it.

**To Reproduce**
1. Open linux garry's mod build.
2. Run a map in beatrun gamemode.
3. Trigger playback of sound located in the subfolder of "mirrorsedge" folder. (Climb up a ladder)
4. See "Failed to load sound "MirrorsEdge/**_subfolder name here_**/**_sound name here_**" error in console.

**Expected behavior**
Play sound.

**Screenshots/Videos**
[**_Video_**](https://github.com/JonnyBro/beatrun/assets/157890839/2897c6bc-9056-49bf-bfc3-679296ec6532)
![error](https://github.com/JonnyBro/beatrun/assets/157890839/5a3095e7-ff2a-4940-acac-57f9f3291e69)

**Additional information:**
 - Game Version: x64
- Game Type: singleplayer and multiplayer

**Additional context**
Sounds are there and they're fine.

**Fix!**
Change capital letters to lowercase letters in subfolders names.

**Comment by JonnyBro** [comment]
I'll check it out but doesn't expect anything. I dont use linux

**Comment by JonnyBro** [comment]
oh wait, it should be an easy fix

**Comment by JonnyBro** [comment]
can you update and check again?

**Comment by Turelk** [comment]
> can you update and check again?
I updated the mod, tested it and it didn't work

**Comment by Turelk** [comment]
![actualfix](https://github.com/JonnyBro/beatrun/assets/157890839/a8184e0e-cb69-4e64-9a62-da7e48d77fd4)
By changing capital letters to lowercase letters, you fix the bug.

**Comment by JonnyBro** [comment]
i'll rename all the folders and their code then, thanks! I forget that Linux is case-sensetive to that (Windows is not)
