### ISSUE TITLE
[Suggestion] SDK, additional options for ladders.

### ISSUE THREAD

**Issue by Turelk** [JonnyBro/beatrun#149]
**Describe the solution you'd like**
I have multiple suggestions:
1. It seems to me a good idea to make a **_SDK for beatrun_**, this should help create working objects when creating a map in hammer. Although this is most likely not easy, but for example, Elevator: Source supplies its own SDK.
2. **_The ability to create stairs without the ability to go upstairs_** (in cases where the stairs are not adjacent to the upper floor.)
(bad explanation, the video shows what I mean.) 
Also the ability to jump from the stairs like in mirror's edge, would be cool, I think.

**Additional context**
Video (Bad quality, for some reason):
https://youtu.be/KL2mF1s6auw?si=oOvqJn9wEnO8xqbd

**Comment by JonnyBro** [comment]
1. I don't know how to do this and I don't really care. You can add beatrun's entities on your map with code, please refer to [Maps](https://github.com/JonnyBro/beatrun/tree/main/beatrun/gamemodes/beatrun/gamemode/Maps) for some examples
2. I'll take a look at what I can do

**Comment by IlikeFreerunning** [comment]
yoo i would love this
