### ISSUE TITLE
[Bug] Removing potentially stuck anim!! Removing potentially stuck anim!! Removing potentially stuck anim!!

### ISSUE THREAD

**Issue by dataesucsdeek** [JonnyBro/beatrun#151]
Removing potentially stuck anim!!
Removing potentially stuck anim!!
Removing potentially stuck anim!!
Removing potentially stuck anim!!
Removing potentially stuck anim!!
Removing potentially stuck anim!!
Removing potentially stuck anim!!
Removing potentially stuck anim!!
Removing potentially stuck anim!!
Removing potentially stuck anim!!
Removing potentially stuck anim!!

and a bit of 
[ERROR] addons/beatrun/gamemodes/beatrun/gamemode/cl/bodyanim.lua:506: Tried to use a NULL entity!
  1. SetNoDraw - [C]:-1
   2. __event - addons/beatrun/gamemodes/beatrun/gamemode/cl/bodyanim.lua:506 (x418)

**Comment by dataesucsdeek** [comment]
i cant move my camera. and my view is stuck in place in a random spot on the map. unless i equip the phys gun. still cant do anything even then

**Comment by dataesucsdeek** [comment]
![gmod_GunSzUsenM](https://github.com/JonnyBro/beatrun/assets/143736106/1989e17b-5abb-4557-affe-e4dbc82bdcdb)

**Comment by dataesucsdeek** [comment]
![gmod_HlsDIi4jHD](https://github.com/JonnyBro/beatrun/assets/143736106/b1f74b15-db2f-46dc-a9cf-498442030b8e)

**Comment by dataesucsdeek** [comment]
I FINALLY FIXED IT
APPARENTLY I HAD TO DOWNLOAD AS ZIP FROM GITHUB. CAUSE THE AUTOMATIC GITHUB CLIENT ONE WAS SUCKASS

**Comment by JonnyBro** [comment]
disable all addons
