### ISSUE TITLE
[Question] Disable/remove near wall hands and camera lock

### ISSUE THREAD

**Issue by LeJuanKM** [JonnyBro/beatrun#152]
When you face next to a wall you put your hands up and your camera gets a vertical lock, you can't look 360° around. I only play single player and have beatrun installed locally.

I want to disable this mechanic animations and camera lock. I found that the animations where you put you hands up can be disabled by 
setting standhandwallright/left/both to false in JumpAnim.lua now I want to disable the camera lock. Where?

**Comment by JonnyBro** [comment]
this was disabled ages ago

**Comment by LeJuanKM** [comment]
Alright, I will. I modified some of the lua files myself and gave the mod some other functionalities, that's why I don't really update anymore.
