### ISSUE TITLE
[Bug] Skill Roll bug

### ISSUE THREAD

**Issue by calebx28** [JonnyBro/beatrun#154]
**Describe the bug**
Skill roll is bugged, when rolling to take no damage from a height, it plays the slide animation after clipping the roll animation, and my character gets stuck

**To Reproduce**
1. Fall from a certain height
2. Click Left Ctrl
3. Watch it to the slide animation
4. Get stuck unless you die

**Expected behavior**
This bug started manifesting the day i am writing this, 6/02/2024, it ocurred in the x86 branch i play in, and then when i tried in the normal game, it persisted.

**Screenshots/Videos**
If applicable, add screenshots or videos to help explain your problem.

**Additional information:**
 - Game Version: Non beta, x86
- Game Type: Singleplayer

**Additional context**
The bug manifested in the map br_turbosvin for the first time, and followed to br_ivory

https://github.com/JonnyBro/beatrun/assets/48849592/30b4dadf-fe2d-4374-a2f5-80f80ddcc8d4

**Comment by calebx28** [comment]
https://github.com/JonnyBro/beatrun/assets/48849592/223e2114-bc16-4508-b8b4-dc6ec0914c55

**Comment by JonnyBro** [comment]
unsub from some addons/restart your game

**Comment by calebx28** [comment]
> Unsub from some addons/restart your game. This will never be fixed on beatrun's end

It was indeed, my addon's problem, thank you!
