### ISSUE TITLE
higher fov options

### ISSUE THREAD

**Issue by IlikeFreerunning** [JonnyBro/beatrun#157]
can you please make higher fov options or at least make fov mods compatible?

**Comment by JonnyBro** [comment]
try changing `100` in [this](https://github.com/JonnyBro/beatrun/blob/3d1f47da96f654ad77f6b2c4550f5646ecb3b1d8/beatrun/gamemodes/beatrun/gamemode/sh/0_Misc.lua#L25) line, maybe this will work
