### ISSUE TITLE
multiplayer

### ISSUE THREAD

**Issue by Wenninc** [JonnyBro/beatrun#16]
So i was playing with my friend, and my friend always was disconnected with this error:Dropped (Nickname) from server (Client sent too much data)

**Comment by JonnyBro** [comment]
It's not the best system for preventing net spamming, maybe your friend has way high ping or slow internet.

https://github.com/JonnyBro/beatrun/blob/9f62794e94771d96e56e6f6d96e6062b1da850c7/beatrun/gamemodes/beatrun/gamemode/sv/KarmaBGone.lua#L19

**Comment by eros71-dev** [comment]
I'm also getting this error as well, we both have 1 GBPS fiber, and also are on the same country, ping never was an issue.
