### ISSUE TITLE
[Bug] Cannot connect to courses database

### ISSUE THREAD

**Issue by ianSteam** [JonnyBro/beatrun#162]
**Describe the bug**
When trying to use Beatrun_LoadCode, i am unable to go to the specified map.

**To Reproduce**
1. Open the Console
2. Run 'Beatrun_LoadCode 'Code found on courses.beatrun.ru''

**Expected behavior**
Send player to specified map

**Screenshots/Videos**
![image](https://github.com/JonnyBro/beatrun/assets/71144872/f1675c63-478f-4f38-bd15-eaaa09caf735)

**Additional information:**
 - Game Version: Chromium x86-64
- Game Type: Singleplayer

**Comment by JonnyBro** [comment]
Error is yellow...
