### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Wisbe** [JonnyBro/beatrun#17]
когда загружашся на мапу вылетает ошибка 
![iNPRNeSH9g](https://github.com/JonnyBro/beatrun/assets/136597982/9ec1bf92-7d72-4125-b18a-6130f283f8bd)

**Comment by JonnyBro** [comment]
VManip установлен?
Похоже на конфликт аддонов

**Comment by Wisbe** [comment]
виманип есть и из аддонов токо моделька

**Comment by relaxtakenotes** [comment]
можно смело игнорить эту ошибку, она ничего не делает
