### ISSUE TITLE
[Not quite a bug] animations i cant find anymore

### ISSUE THREAD

**Issue by D3STROY3R** [JonnyBro/beatrun#171]
**Describe the bug**
About month ago i used to play gmod on home PC but travel now, i installed all my subs on notebook and powershell installed beatrun from this fork. i checked "1" option from animation changer (reanimation project) but it seems like old, before on home PC i had new animation set eg when coiling (jump+ctrl) animation was crossarmed jump, and not straight forward "Kong" with two legs higher than middle of screen, and had hand animation when come close to a wall just like in Mirrors Edge, cant find what animation set was that, MAY be it was not reanimation project but i cant find any info bout what was it then. 
**To Reproduce**

**Expected behavior**
Any ideas bout that animation set?

**Screenshots/Videos**
If applicable, add screenshots or videos to help explain your problem.

**Additional information:**
 - Game Version: x64
- Game Type: singleplayer

**Additional context**

**Comment by JonnyBro** [comment]
MTB changed them because some playermodels look bad with crossarmed jump.
Hand animations on the wall was disabled because of my bad implementation, i *maybe* will remake them
