### ISSUE TITLE
[Bug] FOV issues with some weapons

### ISSUE THREAD

**Issue by LostTrackpad** [JonnyBro/beatrun#179]
**Describe the bug**
FOV behavior appears to not work right with some zoom types (?) after #159 and some subsequent related commits.

**To Reproduce**
1. Launch the game and start _any_ map with the Beatrun gamemode
2. Equip the Camera weapon (Spawnmenu -> Weapons -> Other)
3. Try and zoom in (RMB + move your mouse forwards). Notice that it won't zoom in.

**Expected behavior**
The Camera weapon should be able to zoom in.

**Screenshots/Videos**
Top is idle standing state, middle is aiming down sights, bottom is aiming down sights with [patched FOV behavior](https://github.com/LostTrackpad/beatrun/commit/d365a852d55aaf0dfe3814894e2995ce219189dc).
![Not aiming down sights at proper 120 FOV.](https://github.com/JonnyBro/beatrun/assets/161031457/3b6edc77-2be1-4c28-b018-c2c22600f6e6)
![Aiming down sights. Still keeping non-ADS FOV and glitches out viewmodel.](https://github.com/JonnyBro/beatrun/assets/161031457/17717d47-1d94-45c1-918f-fc13aa011b67)
![Aiming down sights with the FOV behavior patched to work as it should. Notice how it zooms to ~90 FOV and the viewmodel no longer glitches out.](https://github.com/JonnyBro/beatrun/assets/161031457/123a26a9-c445-4f73-a4c3-f8da9b082925)

**Additional information:**
 - Game Version: x86-64, latest update as of April 4th 2024.
- Game Type: Both singleplayer and multiplayer.

**Additional context**
Beatrun FOV was set to 120, though I don't think this is relevant.

Weapon used in screenshots is a TFA Base weapon.

**Comment by LostTrackpad** [comment]
Okay I figured it out: The Camera weapon (and some weapon bases that use a similar zoom in method, and the HL2 zoom) tries to set `CalcView()` FOV but since we're setting it to 120 _constantly_, it can't, and so...this bug happens.

**Comment by LostTrackpad** [comment]
Oops, accidentally closed the issue.

**Comment by JonnyBro** [comment]
HL2's zoom was never intended to work

**Comment by LostTrackpad** [comment]
> HL2's zoom was never intended to work

Okay well maybe not the HL2 zoom, but anything else that (apparently to me anyway) uses the same zoom method.

_(Would mean that the HL2 zoom has to be completely disabled **while keeping everything else working** somehow though...)_

**Comment by JonnyBro** [comment]
I'll take a look into this on weekends. I think I'll just disable HL2's zoom.

**Comment by LostTrackpad** [comment]
HL2 zoom is already disabled in Beatrun normally, it just somehow started working when I tried to fix this (Lua refresh being weird I suppose).

Also another thing I forgot after finding out about it ~2 weeks ago: ARC9 weapons need special handling in the fix because switching away from them causes your FOV to jerk back to `fov_desired`'s value (for example, 120 (`beatrun_fov`) > 100 (my `fov_desired`))

It's like 9PM as I write this over here, I'll correct this later if I figure anything out.

**Comment by LostTrackpad** [comment]
@JonnyBro I think you can unpin this issue now. In case you forgot.

**Comment by JonnyBro** [comment]
Oh yea, thanks
