### ISSUE TITLE
[Bug] <Roll Bug>

### ISSUE THREAD

**Issue by ForGmod** [JonnyBro/beatrun#181]
**Describe the bug**
I Cant roll,it makes me that i cant move

**To Reproduce**
1. Launch gmod and turn beatrun on
2. get to a edge with a ground near it
3. Roll

**Expected behavior**
i expected to move but i cant

**Screenshots/Videos**

https://github.com/JonnyBro/beatrun/assets/138776421/b2d054c0-712e-4a1b-8a94-406c04397a31

**Additional information:**
 - Game Version: chromium, x64
- Game Type: singleplayer

**Comment by JonnyBro** [comment]
Unsub from some addons (primarily weapon bases) and restart your game

**Comment by ForGmod** [comment]
ty it worked
