### ISSUE TITLE
courses dont load

### ISSUE THREAD

**Issue by IlikeFreerunning** [JonnyBro/beatrun#183]
courses don't load anymore for me is this because my api key or something else? if it is my api key i deleted the .txt file that had it so can u resend it to me? heres my profile https://steamcommunity.com/profiles/76561198047965564/ btw i cant accept it by email or anything so can u please just tell me it on here?

**Comment by JonnyBro** [comment]
First of all, update beatrun to latest version. 
Second, join our discord and open a ticket.

**Comment by IlikeFreerunning** [comment]
i cant use discord anymore my dad wont let me please help

**Comment by JonnyBro** [comment]
add me in steam
