### ISSUE TITLE
????

### ISSUE THREAD

**Issue by IlikeFreerunning** [JonnyBro/beatrun#184]
whenever i start walking it gets super choppy and laggy??

**Comment by JonnyBro** [comment]
sad

**Comment by IlikeFreerunning** [comment]
do you just not care? why even have a bug and suggestions area

**Comment by JonnyBro** [comment]
I dont read minds and i dont see your screen, i dont know what are you talking about. Noone ever reported this, this is a you issue. I can only suggest checking your addons and/or disabling all of them
