### ISSUE TITLE
[Bug] <I don't see the interface and XP>

### ISSUE THREAD

**Issue by tihnar228** [JonnyBro/beatrun#189]
I don't see the "hud" and the experience counter. in the settings hud and experience counter are enabled

**Comment by JonnyBro** [comment]
Disable all HUD related addons, reinstall beatrun, restart the game. Something from this list could help

**Comment by tihnar228** [comment]
> Отключите все дополнения, связанные с HUD, переустановите Beatrun, перезапустите игру. Что-то из этого списка может помочь

Thank you. it helped me
