### ISSUE TITLE
option to toggle between the vanilla beatrun font and the font you currently have?

### ISSUE THREAD

**Issue by skozzu** [JonnyBro/beatrun#19]

**Comment by JonnyBro** [comment]
I didn't change any fonts in this project. Only font related change here is speedometer uses HUD's font now

**Comment by skozzu** [comment]
so how do i change back the speedometer font back to the vanilla version?

**Comment by JonnyBro** [comment]
https://github.com/JonnyBro/beatrun/blob/8ef685b31431116314746bef752ca0af6aa8a17a/beatrun/gamemodes/beatrun/gamemode/sh/Checkpoints.lua#LL252C2-L252C2

**Comment by skozzu** [comment]
alr thanks
