### ISSUE TITLE
[Bug] Ghost player??

### ISSUE THREAD

**Issue by Lumyz123** [JonnyBro/beatrun#190]
**Describe the bug**
When I play the game on beatrun I phase through EVERYTHING that is possible to phase through via disabling collisions

**To Reproduce**
1. Start playing Beatrun
2. Try to walk into literally anything (NPC, Door, Prop)

**Expected behavior**
I expected to be able to collide with stuff??

**Screenshots/Videos**
![d1_trainstation_010000](https://github.com/JonnyBro/beatrun/assets/168821758/1da917e6-d07c-48aa-946c-4c64d2a385fc)

**Additional information:**
 - Game Version: I tried on every one, didn't change on any one of them
- Game Type: singleplayer

**Additional context**
I disabled the HUD, don't think that was supposed to change anything though.

**Comment by Lumyz123** [comment]
The picture showcased this cuz as you can see collisions are enabled

**Comment by JonnyBro** [comment]
addons conflict

**Comment by Lumyz123** [comment]
> addons conflict, check your addons

does it work normally for you?

**Comment by Lumyz123** [comment]
Alright, it appears i DID have a conflicting addon. Thank you so much JonnyBro for helping

**Comment by Lumyz123** [comment]
Imma just close this
