### ISSUE TITLE
[Suggestion] Toggleable ability to reload/respawn when r is pressed

### ISSUE THREAD

**Issue by runaroundontheground** [JonnyBro/beatrun#192]
I keep accidentally pressing r and it resets me to the beginning of whatever map I was playing on. This only happens while holding the runner hands, so it's not super common but it's annoying when it happens.

I'd like to have a console command or a toggle box in the q menu to enable/disable this functionality.

I tried unbinding r, but it seems it's tied to the reload key, so that didn't work. I've also looked through a bit of the code to try to find what causes this, but I'm not really sure where it is.

If this already exists, then idk where to find it.

**Comment by JonnyBro** [comment]
Comment out or remove this entire function and you're good
https://github.com/JonnyBro/beatrun/blob/main/beatrun%2Fgamemodes%2Fbeatrun%2Fentities%2Fweapons%2Frunnerhands%2Fshared.lua#L398

**Comment by runaroundontheground** [comment]
It worked!
Thanks
An in-game option might be good for other users, but I don't need it now
