### ISSUE TITLE
problem with fov

### ISSUE THREAD

**Issue by ikariustrxsh** [JonnyBro/beatrun#193]
with some weapons or objects when I switch to the default hands of the mod the error appears

[beatrun] RunConsoleCommand: Command is blocked! (fov_desired)
    1. unknown - addons/beatrun/gamemodes/beatrun/entities/weapons/runnerhands/shared.lua:103
        2. Give - [C]:-1
            3. RunClass - addons/beatrun/gamemodes/beatrun/gamemode/player_class/player_beatrun.lua:149
                4. Call - gamemodes/base/gamemode/player.lua:292
                    5. PlayerSpawn - gamemodes/base/gamemode/player.lua:246
                        6. unknown - addons/beatrun/gamemodes/beatrun/gamemode/sv/spawn.lua:80

**Comment by JonnyBro** [comment]
Something is blocking beatrun from changing your FOV, `fov_desired` is not listed on blocked commands. I suggest you disabling all your addons. Let me know if this works

**Comment by ikariustrxsh** [comment]
> Something is blocking beatrun from changing your FOV, `fov_desired` is not listed on blocked commands. I suggest you disabling all your addons. Let me know if this works

still the same :(
[beatrun] RunConsoleCommand: Command is blocked! (fov_desired)
    1. unknown - addons/beatrun/gamemodes/beatrun/entities/weapons/runnerhands/shared.lua:103
        2. Give - [C]:-1
            3. RunClass - addons/beatrun/gamemodes/beatrun/gamemode/player_class/player_beatrun.lua:149
                4. Call - gamemodes/base/gamemode/player.lua:292
                    5. PlayerSpawn - gamemodes/base/gamemode/player.lua:246
                        6. unknown - addons/beatrun/gamemodes/beatrun/gamemode/sv/spawn.lua:80

**Comment by JonnyBro** [comment]
fixed
