### ISSUE TITLE
my pov is in the ground

### ISSUE THREAD

**Issue by sumgoofydumazz** [JonnyBro/beatrun#196]
sorry if its not very specific but basically, when i play sandbox its fine.

- 
![gm_construct0000](https://github.com/JonnyBro/beatrun/assets/172090053/f74f36a0-0288-4d23-8603-fd3f5ebb1240)

however when i change my game mode to beatrun i get this
![gm_construct0001](https://github.com/JonnyBro/beatrun/assets/172090053/d1b27296-d553-41c0-a909-cd0730274881)
![gm_construct0002](https://github.com/JonnyBro/beatrun/assets/172090053/37d9d095-b34a-44d3-8a26-156acb2469fa)
dont know what happened, i was playing a workshop map, but for some reason either i died or something, that happened.

any help will be appreciated.

**Comment by sumgoofydumazz** [comment]
i just want to clarify some stuff,
1. yes i have tried verifying the games cache
2. i have reinstalled beatrun, same issue
3. i tried automatic installing but for some reason powershell came up with "error code 522." there was more text but i couldnt be bothered to copy it all.
4.

**Comment by JonnyBro** [comment]
addons conflict

**Comment by sumgoofydumazz** [comment]
hey thanks man, but uh do you know what kind of mods would cause conflict with beatrun or should i just disable all mods?

**Comment by JonnyBro** [comment]
Try disabling some random addons, it could be the problem with hooks order. But mainly everything that messes with the camera or/and player movement is considered conflict
