### ISSUE TITLE
Conflict with VIVO | Health Overhaul

### ISSUE THREAD

**Issue by DCPshka9371** [JonnyBro/beatrun#198]
**Describe the bug**
Stack animation with addon VIVO. When you do quick turn with Runner Hands and roll back, animations play twice and you stuck in stand pose(or lay pose)

**To Reproduce**
1. Do quick turn with Runner Hands
2. Roll back
3. Get stuck

**Expected behavior**
Um. They probably fixed it or found a bug why this happens.

**Screenshots/Videos**
https://youtu.be/ArjTk125M34

**Additional information:**
 - Game Version: non-beta
- Game Type: Singleplayer

**Comment by JonnyBro** [comment]
Try disabling/removing other addons, I don't think that VIVO is the problem here

**Comment by DCPshka9371** [comment]
Oh. You're right. Sorry for the misinformation.

**Comment by DCPshka9371** [comment]
> Try disabling/removing other addons, I don't think that VIVO is the problem here. It's a known issue and cause of it is unknown, right now I think it's somehow related to hooks load order

I found conflict VIVO with ARC9 weapon base. Something is preventing them from being together and animation broken
