### ISSUE TITLE
NOT an issue, just suggestions

### ISSUE THREAD

**Issue by demiantmb** [JonnyBro/beatrun#20]
1. try adding proper thirdperson animations, it would be 100% painful and buggy to do so, but it would make watching others parkour look less confusing, especially if they dive or fall on their asses

2. also try adding falldamage animations, it would **at least** add some cool visuals, and would just look better **entirely** than moonwalking after not rolling

**Comment by JonnyBro** [comment]
1. i don't do animations
2. i don't do animations
