### ISSUE TITLE
[Bug] last weapon used key doesn't work while runner hands are equipped

### ISSUE THREAD

**Issue by redfoxlol** [JonnyBro/beatrun#202]
**Describe the bug**
you can't quick swap to to your last weapon with the last weapon used key while holding the runner hands

**To Reproduce**
1) load into any map in the beatrun gamemode
2) get any other weapon in your inventory
3) equip the other weapon and then switch back to runner hands
4) press the last weapon used key
5) nothing will happen

**Expected behavior**
the last weapon you used will be equipped

**Additional context**
i have last weapon used bound to mouse4 if that helps

**Comment by c4nkerm3me** [comment]
Just a question, did you try re-binding mouse4 to anything else?
Also I dont know if thats the swep that causes the issue or some different code, but I (as a contributor) can try fixing it.

**Comment by redfoxlol** [comment]
yeah, just tried rebinding it to h now and it still doesn't work

**Comment by JonnyBro** [comment]
Fixed in https://github.com/JonnyBro/beatrun/commit/cd4af324df4cf2c4e94990919305a7e55f9a9b68
