### ISSUE TITLE
[Bug] Sliding and getting stuck when trying to get up from jumping quick turn with S

### ISSUE THREAD

**Issue by ZeroJyllmeiko** [JonnyBro/beatrun#204]
**Describe the bug**
When I do the quick turn from the air and try to get up with S, I somehow slide. Then I get stuck in place, even if I switch weapons.

**To Reproduce**
1. Load any map in Beatrun mode
2. Jump forward and use RMB
3. Try to get up with S.

**Expected behavior**
Player gets up and can still move

**Additional information:**
 - Game Version: [x86-x64]
- Game Type: Singleplayer

**Additional context**
There are no conflicting addons.
I have reinstalled this mod, and it still does it.

**Comment by EmilianoRacerPlayer** [comment]
I also did the same thing that when I slid I got stuck, it was a good thing although knowing this mod then I installed it the last time on 07/10/2024 of this month and what bothers me is that when you run and move backwards my character moves I was stuck, I couldn't move well, I even set NPCs to kill me quickly and the only thing it does is make our character move backwards and make an animation, as I will say, an animation of when you fly out and hit the ground and when they shoot, the character goes back. I couldn't get up at all! I hope they fix it

**Comment by JonnyBro** [comment]
Disable some addons, especially that can modify your movement
