### ISSUE TITLE
[Suggestion] Add toggle "Allow Infected Players to Grapple"

### ISSUE THREAD

**Issue by Mistery1307** [JonnyBro/beatrun#206]
Hello! I'm a really big fan of Beatrun from the last year or so of playing the online multiplayer gamemodes with friends(I've even gotten to LAN it a couple times), and over my time playing it, I found I always played with some slight modifications to the code.

One of my favorite things to change was making infected players able to use the grappling hook. It sounds broken at first, but I find it actually changes the balance in a really fun way.
Without this change enabled, I find Infected players can often spend the entire timer running around without actually finding anyone, and so the game just kinda ends way too early, so it's boring for all players. With this change, though, the Infected players breeze around the map until they find a player to chase, and I find that because of Beatrun's really tight movement in enclosed spaces, the grapple doesn't really give the Infected players an incredibly unfair advantage if the running player gets tricky with going in and out of buildings, etc.

I modified a couple lines of code roughly as shown below(I did it a while ago so I'd have to do some digging to remember out exactly all the changes it needs), and I think it'd be really great if someone who created all the recent UI variables could turn this into a toggle like the timer and stuff.
![image](https://github.com/user-attachments/assets/45e5a1a3-77dc-4656-98c5-c5e2913b19f6)

**Comment by JonnyBro** [comment]
I'm not planning this, but you can do whatever you want.
