### ISSUE TITLE
[Bug] unable to load courses via the course database

### ISSUE THREAD

**Issue by redfoxlol** [JonnyBro/beatrun#207]
**Describe the bug**
i am unable to load courses via the courses database

**Screenshots/Videos**
![image](https://github.com/user-attachments/assets/83f5a0f3-ab92-4103-a269-f701c71a2501)
this is the error i get whenever i try to load a course

**Additional information:**
i'm on the x86-64 branch of gmod

**Comment by JonnyBro** [comment]
What does `Beatrun_Domain` returns? @redfoxlol

**Comment by JonnyBro** [comment]
Also, I recommend joining our Discord for faster replies!

**Comment by redfoxlol** [comment]
beatrun_domain is set to courses.beatrun.ru

**Comment by JonnyBro** [comment]
Change it to default. Also don't forget to keep your beatrun up to date
