### ISSUE TITLE
[Bug] <No HUD and XP in Beatrun>

### ISSUE THREAD

**Issue by Stendi078** [JonnyBro/beatrun#208]
**Describe the bug**
I have already tried many ways: I downloaded Beatrun from GitHub, from the Steam workshop, but no matter how hard I tried, the result was the same - the lack of interface and XP, as well as there is no way to switch to build mode and there is no window with courses. There are no addons that could prevent this. What to do?

**Comment by JonnyBro** [comment]
Join our Discord and ping me with a screenshot of your issue
