### ISSUE TITLE
[Suggestion] Mirror's Edge (2008) accurate speed

### ISSUE THREAD

**Issue by Patrxgt** [JonnyBro/beatrun#211]
**Is your feature request related to a problem? Please describe.**
It would be nice to have an option to toggle Mirror's Edge-like movement speed for all of the actions, that are present in this mod.

**Describe the solution you'd like**
A button, that would allow to toggle between Mirror's Edge-like movement speed and the custom one (original mod's behaviour).

**Describe alternatives you've considered**
An alternative to that would be to just change speed values to use Mirror's Edge-like movement speed by default (eg. using 380 speed units instead of 325).

**Additional context**
[Here](https://www.youtube.com/watch?v=tEIJh32lrjg) you can find an example of the character's acceleration and speed in the original game.

**Comment by JonnyBro** [comment]
Use speed limit variable
