### ISSUE TITLE
[Bug] Can't springboard

### ISSUE THREAD

**Issue by GeoLei2u** [JonnyBro/beatrun#214]
**Describe the bug**
When I hold space on anything object it just vaults when I need to springboard

**To Reproduce**
1. Go to any object
2. Run and hold space
3. Doesn't springboard

**Expected behavior**
Meant to jump really high

**Screenshots/Videos**
I don't think a video is needed

**Additional information:**
Non beta, x64, single player

**Additional context**
Downloaded some of the workshop stuff at the top of the page when searching beatrun

**Comment by JonnyBro** [comment]
Video

**Comment by GeoLei2u** [comment]
https://youtu.be/1ZKsou__s3c

**Comment by JonnyBro** [comment]
Disable all your addons. There is literally a constant error spam, but you don't see it behind your keystrokes thing (beatrun already has those. You don't need to use 2 of those)

**Comment by GeoLei2u** [comment]
Oh i only now found out i had this addon called "beat the run" my friend made it install it so i could play with him but now i deleted it. It works now.

**Comment by JonnyBro** [comment]
> Oh i only now found out i had this addon called "beat the run" my friend made it install it so i could play with him but now i deleted it. It works now.

Great! "Beat the run" was my attempt on uploading beatrun to workshop but it got DMCAd in like 10 minutes
