### ISSUE TITLE
[Bug] Broken roll after wallrun

### ISSUE THREAD

**Issue by Patrxgt** [JonnyBro/beatrun#218]
**Describe the bug**
After any kind of longer fall and trying to break the fall with a roll, player's character does the slide and stops moving in any way (even with noclip).

**To Reproduce**
1. Go in-game with Beatrun loaded.
2. Run up the wall.
3. Do the 180° spin.
4. Jump off the wall.
5. Press crouch button when near landing.

**Expected behavior**
Player's character should roll on the ground.

**Screenshots/Videos**
[Here](https://streamable.com/smn95c)'s a video.

**Additional information:**
 - Game Version: Latest "x86-64 - Chromium + 64 bit binaries" build.
 - Game Type: Singleplayer.

**Additional context**
Changing animations between old ones and new ones unstucks the character, but it loses it's hands.

**Comment by JonnyBro** [comment]
You can try this:
1. Restarting the game
2. Removing/installing some addons.

This happens because of hooks load order, I don't have any plans for this.
