### ISSUE TITLE
simple, please make it so you can change kph to mph

### ISSUE THREAD

**Issue by SpaceyKitteNMeow** [JonnyBro/beatrun#220]
please make it so you can change kph to mph

**Comment by UnderSet** [comment]
I think I'll do this one this weekend. Should be easy.

Also uh...just asking, why do you want this?

**Comment by LostTrackpad** [comment]
I think I'll do this one this weekend, should be easy to make.

Also, uh, why do you want this? Just curious.

**Comment by SpaceyKitteNMeow** [comment]
I’m sorry, but I used a HUD’s built in speedometer. Thanks. 
I just wanted it because  I’m American (rahhh)

**Comment by relaxtakenotes** [comment]
added some options, including hammer units. it's in dev rn but will push later
