### ISSUE TITLE
[Bug] <Add a title here!>

### ISSUE THREAD

**Issue by SpaceyKitteNMeow** [JonnyBro/beatrun#221]
**Describe the bug** (including how to reproduce)
"putting your hands out and flying on your tummy" then letting go of those keys, after sliding, you're stuck..

**Expected behavior**
not to get stuck

**Screenshots/Videos**
uh, my monitor is fricked up with HDR, so if I record anything you'll be seeing what a flashbang looks like.

**Additional information:**
x64 build

**Comment by JonnyBro** [comment]
https://github.com/JonnyBro/beatrun/issues/218#issuecomment-2400401210
