### ISSUE TITLE
[Suggestion] Add toggle "Climbing only with runnerhands"

### ISSUE THREAD

**Issue by cafeprogram** [JonnyBro/beatrun#222]
When you hold a gun, crowbar or something else, you can still climb up walls or cling to edges. I checked the code and found that this is not a bug, that's how it works, but it looks a bit strange if you're not someone with four hands.
﻿
There was a code in the previous beatrun code that restricted non runnerhands from climbing,but it was removed and still doesn't work even after being added back.
I'm not sure if this was changed to make players more flexible, but it would be great if there were a toggle.

**Comment by relaxtakenotes** [comment]
added in dev, gonna push later
