### ISSUE TITLE
[Bug] slide after backflop (Phoenix Rose)

### ISSUE THREAD

**Issue by CootieDwagon** [JonnyBro/beatrun#227]
**Describe the bug**
when run, jump and backflop, if you are holding the ctrl key while you do this you will instantly trigger a slide, causing your screen to do a slight glitch for a split second

**To Reproduce**
1. run forward
2. jump and right click to trigger backflop animation
3. hold "ctrl" during the backflop animation
4. you will trigger a slide

**Expected behavior**
i expected this to not happen as it's quite jaring when it happens

**Screenshots/Videos**

https://github.com/user-attachments/assets/16962b4e-66fb-4321-821c-b2653237ff2e

**Additional information:**
 no other mods installed other than default Beatrun and Faith PM (the most up to date version of Beatrun as of today)
if it would be possible to "prevent" the use of the "ctrl" key for a while once the player has triggered the backflop animation?

**Additional context**
none needed

**Comment by relaxtakenotes** [comment]
fixed. will push soon
