### ISSUE TITLE
if you press S after falling down, it causes you to slide/bounce upwards and softlocks you until you killbind

### ISSUE THREAD

**Issue by skozzu** [JonnyBro/beatrun#23]
https://github.com/JonnyBro/beatrun/assets/136962881/e0d2e841-1edf-49bc-9a2b-fedcbec931a6

**Comment by skozzu** [comment]
normally you're supposed to roll backwards into standing up

**Comment by JonnyBro** [comment]
Does this happens on master version? Because I can't replicate that

**Comment by skozzu** [comment]
yes

**Comment by JonnyBro** [comment]
cant replicate, so /shrug. Maybe try disabling all addons except beatrun and vmaniprework

**Comment by skozzu** [comment]
weird, i havent added any addons before i had updated beatrun, its probably just me

**Comment by JonnyBro** [comment]
> weird, i havent added any addons before i had updated beatrun, its probably just me afaik i dont have any incompatible addons as shown in Addon_Warnings

This list doesn't contain all the incompatible addons because it will take ages to find them
