### ISSUE TITLE
[Bug] <Why Does VirusTotal flag the file as Trojan?>

### ISSUE THREAD

**Issue by SippyCuppy** [JonnyBro/beatrun#230]
I saw a comment that said this version of Beatrun was flagged as a trojan by VirusTotal.

I didn't believe this until i tried it myself

![image](https://github.com/user-attachments/assets/96b6ee62-90bc-42fc-9507-e386c8d5997e)

**Comment by relaxtakenotes** [comment]
1) You're scanning the zipfile instead of scanning individual files. Antiviruses have a tendency to flag certain archives due to them possibly containing malware signatures.
2) MaxSecure is a noname indian antivirus. Do you believe it more than, say, malwarebytes, kaspersky or bitdefender?
