### ISSUE TITLE
Slide softlock

### ISSUE THREAD

**Issue by kuildor** [JonnyBro/beatrun#24]
If you press Shift in the air you'll slide and got softlocked

Same with roll backwards after falling down

Video: https://youtu.be/y5gZoQw9FTI (I HATE GITHUB LIMITATIONS)

Tested on lastest commit (bf8f071)

**Comment by kuildor** [comment]
and yea sorry for bs quality, recorded on potato

**Comment by skozzu** [comment]
do you have the body looting addon? remove it
