### ISSUE TITLE
Some issues with 'falling back'

### ISSUE THREAD

**Issue by cafeprogram** [JonnyBro/beatrun#25]
When the player holds the runner hands and presses the right button at a certain speed (greater than 8km/h or non walking speed?), the player's backward animation will become a sliding shovel when touching the ground.

Players holding any weapon will not encounter this situation, but there will still be some issues.

(https://youtu.be/3p3DAQ-Y_ZQ)]

**Comment by JonnyBro** [comment]
Can't replicate, check out your addons, maybe some are conflicting with beatrun

**Comment by cafeprogram** [comment]
In the video presentation, I only used Third Person Enhanced, one character, and one UI enhancement mod

In fact, if TPE is not used, there will be more bugs appearing, such as the perspective of falling into the ground when standing up backwards; The character's neck is broken;

I'm not sure if these are real bugs or other issues (such as a BEATRUN LUA alarm, but it doesn't seem to affect its operation). If you need it, I will upload videos without using any mods and submit LUA errors.

According to the original Beatrun requirements, my GMOD runs on 64 bit and can accommodate up to 2 players when starting the game. If there are any pre requirements for this Beatrun, please let me know.

**Comment by JonnyBro** [comment]
It's know that my fork work better on non-beta version of the game
