### ISSUE TITLE
holding S and pressing space while laying down will do this pretty funny glitch

### ISSUE THREAD

**Issue by skozzu** [JonnyBro/beatrun#27]
https://github.com/JonnyBro/beatrun/assets/136962881/0b89a14c-b2ca-498f-9ab9-f366779ffa91

**Comment by skozzu** [comment]
and if you're asking, yes i'm doing this on your version

**Comment by JonnyBro** [comment]
Can't reproduce. What is your game version, do you have any VManip based mods?

**Comment by skozzu** [comment]
iirc, i recorded this video without any addons except for beatrun and vmanipprework
