### ISSUE TITLE
roll back bug

### ISSUE THREAD

**Issue by kulisek8cz** [JonnyBro/beatrun#29]
When i'm laying on my back and i try to roll back it glitches out and i have to get myself killed for me to be able to move again. When i try to roll with something diferent than unarmed it works normaly.

1. jump
2. click the RMB
3. press s

Here is a video: https://medal.tv/games/garrys-mod/clips/1iegniJ2uMjtbG/d1337wCnFHyp?invite=cr-MSxSdEEsODIxNjQyNjks

**Comment by kulisek8cz** [comment]
I just realized a guy before me had the same issue sorry for not noticing.

**Comment by kulisek8cz** [comment]
b

**Comment by kulisek8cz** [comment]
Oops didn't notice somebody submitted this before me (the closing and reopening was an accident idk how this works)

**Comment by skozzu** [comment]
> Oops didn't notice somebody submitted this before me (the closing and reopening was an accident idk how this works)

remove body looting, disable every addon
