### ISSUE TITLE
Multiplayer animation dosen't work

### ISSUE THREAD

**Issue by K0fy1233** [JonnyBro/beatrun#31]
When playing multiplayer you don't see the other players animation the same with third person.
(If there is a easy fix or if it this a bug when playing multiplayer I hope there is a way to repair this)
![bay_40002](https://github.com/JonnyBro/beatrun/assets/88611822/3be0224a-8067-47ee-a5e3-e64ff0fc36d8)

**Comment by K0fy1233** [comment]
Example when holding the wall

**Comment by JonnyBro** [comment]
It's not a bug and there is no easy fix, I need to rewrite whole animations system and remake animations to make them for third person.
