### ISSUE TITLE
[Bug] Sometimes animation of sliding under incline and on high speed dissapearing

### ISSUE THREAD

**Issue by RedyRT** [JonnyBro/beatrun#32]
**Describe the bug**
Аnimation of sliding under incline and on high speed is dissapearing.

**To Reproduce**
Do my movings like in the video

**Expected behavior**
Like in the video

**Screenshots/Videos**
[2023-07-18 01-50-19.webm](https://github.com/JonnyBro/beatrun/assets/64935439/151d764c-bbd1-4151-be83-491af6d89804)

**Additional information:**
- Game Version: [chromium x64]
- Game Type: [singleplayer]

**Additional context**
All my addons is disabled in the list.

P.S keep doing it guys, you are doing good work here and the addon works perfectly, basically addon doesnt should have shitty datae dll files to work, it works perfectly without those dlls, datae fr totally nerd forces people to download his virus dlls to make this addon work

**Comment by skozzu** [comment]
it usually happens with ramps, but when you're sliding normally, it shouldn't happen

**Comment by JonnyBro** [comment]
I'll have a look into that when I have some time, thanks for reporting!

**Comment by JonnyBro** [comment]
Should be fixed with latest commit! Let me know if you get this error again

**Comment by RedyRT** [comment]
> Should be fixed with latest commit! Let me know if you get this error again

Yep, its fixed now.
