### ISSUE TITLE
[Suggestion]  Alt branch with the old animations

### ISSUE THREAD

**Issue by AtaKanK4467** [JonnyBro/beatrun#35]
I prefer the old animations but since i lost the file, i cant play with it. Can you add a branch without MTB's animations.

**Comment by JonnyBro** [comment]
Will not do, sorry. You can ask how to return old animations in our Discord tho!

**Comment by AtaKanK4467** [comment]
i actually asked on dc too

**Comment by AtaKanK4467** [comment]
thanks!
