### ISSUE TITLE
[Bug] Lua error while deleting checkpoint through buildmode menu

### ISSUE THREAD

**Issue by RedyRT** [JonnyBro/beatrun#36]
**Describe the bug**
Lua error while deleting checkpoint in buildmode menu (which happened after update)

**To Reproduce**
1. Go to buildmode menu
2. Click on checkpoint and create some couple of it
3. Now just delete one of them (checkpoint)

**Expected behavior**
[beatrun] addons/beatrun/gamemodes/beatrun/entities/entities/tt_cp/shared.lua:106: Tried to use a NULL entity!
    1. GetPos - [C]:-1
        2. unknown - addons/beatrun/gamemodes/beatrun/entities/entities/tt_cp/shared.lua:106

**Screenshots/Videos**
[2023-07-23 17-47-09.webm](https://github.com/JonnyBro/beatrun/assets/64935439/49ce405f-9f4e-40aa-97b0-9ab4a58ecc8b)

**Additional information:**
 - Game Version: [chromium x64]
- Game Type: [singleplayer]

**Additional context**
_

**Comment by JonnyBro** [comment]
It's not critical, you can ignore that

**Comment by RedyRT** [comment]
> It's not critical, you can ignore that

yeah, but lua error still not cool i guess.

**Comment by JonnyBro** [comment]
I'll have a look into it later, for now just ignore it =)

**Comment by JonnyBro** [comment]
fixed in https://github.com/JonnyBro/beatrun/commit/fc75bd10a0d7e5cb232483afef6bcb3c5b5e626d
Sorry for 2 month of waiting, was busy with work
