### ISSUE TITLE
[Bug] Firstperson viewmodel breaking while climbing on func_useableladder (just ladders i mean) on the maps 

### ISSUE THREAD

**Issue by RedyRT** [JonnyBro/beatrun#37]
**Describe the bug**
Firstperson viewmodel just breaking while climbing a ladder

**To Reproduce**
1. Go to 'any map that contains "func_useableladder"' (mine is gpk_freecity)
2. Try to climb up
3. See error

**Expected behavior**
Your firstperson viewmodel will break

**Screenshots/Videos**
[2023-07-24 00-59-02.webm](https://github.com/JonnyBro/beatrun/assets/64935439/fc4117d7-a996-4ad4-a8bf-a2cefe280e04)

**Additional information:**
 - Game Version: [chromium x64]
- Game Type: [singleplayer]

**Additional context**
_

**Comment by RedyRT** [comment]
I can notice that, it usually happens on some maps

**Comment by RedyRT** [comment]
And sometimes it can break camera view
[2023-07-24 14-47-50.webm](https://github.com/JonnyBro/beatrun/assets/64935439/07ee11b9-c13d-4254-b75a-998812a6394e)

**Comment by JonnyBro** [comment]
They are not intended to be used in Beatrun, so I would not fix them, sorry!
