### ISSUE TITLE
[Bug] Sitting animation is breaking when sitting and pressing key S then A

### ISSUE THREAD

**Issue by RedyRT** [JonnyBro/beatrun#38]
**Describe the bug**
Animation just breaking while sitting and pressing key S then A

**To Reproduce**
1. CTRL
2. And press key S
3. Then after this press key A or D (it doesnt matter same bug)

**Expected behavior**
You will see that your sitting animation going just to walking animation when you are sitting

**Screenshots/Videos**
[2023-07-24 01-16-34.webm](https://github.com/JonnyBro/beatrun/assets/64935439/d01e42dd-3d99-4187-be8f-4d608d3a4296)

**Additional information:**
 - Game Version: [chromium x64]
- Game Type: [singleplayer]

**Additional context**
_

**Comment by JonnyBro** [comment]
Should be fixed with new crouching animations!

**Comment by RedyRT** [comment]
> Should be fixed with new crouching animations (Use installer to install Beatrun Reanimated Project, they are not fixed in OG anims)!

Its still even with reanimated anims, same bug
