### ISSUE TITLE
[Bug] Missing sound when falling on hands

### ISSUE THREAD

**Issue by RedyRT** [JonnyBro/beatrun#39]
**Describe the bug**
Theres totally supposed to be sound i think when falling on hands

**To Reproduce**
When falling, just press only CTRL and you will see

**Expected behavior**
Just missing sounds of falling on hands

**Screenshots/Videos**

https://github.com/JonnyBro/beatrun/assets/64935439/86d351f4-31d1-44d8-bff4-06ae8b1097f4

**Additional information:**
 - Game Version: [chromium x64]
- Game Type: [singleplayer]

**Additional context**
_

**Comment by JonnyBro** [comment]
Seems like some addons conflict, I don't have that issue

**Comment by RedyRT** [comment]
> Seems like some addons conflict, I don't have that issue on both versions. All landing have pretty much the same code, so I don't think the issue is the code

I disabled all addons that i have, but experiencing same thing like in the video

**Comment by RedyRT** [comment]
I just realized that, it depends on which material i am this sound, for some materials this sound not appearing

**Comment by RedyRT** [comment]
Fixed
