### ISSUE TITLE
[Bug] Lua error when starting multiplayer

### ISSUE THREAD

**Issue by RedyRT** [JonnyBro/beatrun#40]
**Describe the bug**
Lua error when starting multiplayer and the error appears when you first spawn

**To Reproduce**
1. Go to 'multiplayer mode in garry's mod'

**Expected behavior**
[beatrun] addons/beatrun/gamemodes/beatrun/gamemode/sh/checkpoints.lua:273: attempt to perform arithmetic on local 'w' (a nil value)
  1. v - addons/beatrun/gamemodes/beatrun/gamemode/sh/checkpoints.lua:273
   2. unknown - lua/includes/modules/hook.lua:96

**Screenshots/Videos**
![изображение](https://github.com/JonnyBro/beatrun/assets/64935439/1af82ff4-b59e-47f4-bb9a-4ccc922a183a)

**Additional information:**
 - Game Version: [chromium x64]
- Game Type: [multiplayer]

**Additional context**
All addons are disabled also

**Comment by RedyRT** [comment]
And for some reason overdrive not toggling up in multiplayer mode when E+LMB

**Comment by JonnyBro** [comment]
I'll take a look into it after work, thanks!

**Comment by JonnyBro** [comment]
What is your's "Beatrun_HUDHidden" convar set to?

**Comment by JonnyBro** [comment]
Or better all your settings from Tool Menu -> Beatrun

**Comment by RedyRT** [comment]
> Or better all your settings from Tool Menu -> Beatrun

![изображение](https://github.com/JonnyBro/beatrun/assets/64935439/bac8de65-423c-4e44-a0ac-9a36f954bba5)
![изображение](https://github.com/JonnyBro/beatrun/assets/64935439/9d5c80e8-ed6a-422c-8c77-fdcd82201dd2)
![изображение](https://github.com/JonnyBro/beatrun/assets/64935439/3b96b195-b2cb-43bd-9cbd-a09c6f63f161)
![изображение](https://github.com/JonnyBro/beatrun/assets/64935439/d5deb7db-ed83-477c-a36d-75800bc9edb8)
![изображение](https://github.com/JonnyBro/beatrun/assets/64935439/b31dd933-b450-450e-b30d-cde68ccb2c55)
![изображение](https://github.com/JonnyBro/beatrun/assets/64935439/f9aa1110-6ccd-48fe-8c74-6784a048e5dd)

**Comment by JonnyBro** [comment]
Can you try this on latest commit?

**Comment by RedyRT** [comment]
> Can you try this on latest commit? If it still persist, I suspect an addon conflict, maybe some HUD addon

same error, i have no clue, all of my addons are disabled and i dont have HUD addon. I also installed latest commit btw, i can only say that its not spamming that much when starting multiplayer 
![изображение](https://github.com/JonnyBro/beatrun/assets/64935439/881a0506-3361-4f24-8ab6-e15bc4a3e4e9)

**Comment by RedyRT** [comment]
> > > Can you try this on latest commit? If it still persist, I suspect an addon conflict, maybe some HUD addon
> > 
> > 
> > same error, i have no clue, all of my addons are disabled and i dont have HUD addon. I also installed latest commit btw, i can only say that its not spamming that much when starting multiplayer ![изображение](https://user-images.githubusercontent.com/64935439/256280908-881a0506-3361-4f24-8ab6-e15bc4a3e4e9.png)
> 
> Oh also i guess its spamming only when im setting Beatrun_HUDHidden 2 convar and its start spamming like in this picture down here ![изображение](https://user-images.githubusercontent.com/64935439/255695201-1af82ff4-b59e-47f4-bb9a-4ccc922a183a.png)

this is really odd since all of my addons are disabled and its just says theres an error somewhere

**Comment by RedyRT** [comment]
> > > > Can you try this on latest commit? If it still persist, I suspect an addon conflict, maybe some HUD addon
> > > 
> > > 
> > > same error, i have no clue, all of my addons are disabled and i dont have HUD addon. I also installed latest commit btw, i can only say that its not spamming that much when starting multiplayer ![изображение](https://user-images.githubusercontent.com/64935439/256280908-881a0506-3361-4f24-8ab6-e15bc4a3e4e9.png)
> > 
> > 
> > Oh also i guess its spamming only when im setting Beatrun_HUDHidden 2 convar and its start spamming like in this picture down here ![изображение](https://user-images.githubusercontent.com/64935439/255695201-1af82ff4-b59e-47f4-bb9a-4ccc922a183a.png)
> 
> this is really odd since all of my addons are disabled and its just says theres an error somewhere

note: i just deleted all of my addons and  deleted all of its cache, the error is still there somehow

**Comment by RedyRT** [comment]
> > > > > Can you try this on latest commit? If it still persist, I suspect an addon conflict, maybe some HUD addon
> > > > 
> > > > 
> > > > same error, i have no clue, all of my addons are disabled and i dont have HUD addon. I also installed latest commit btw, i can only say that its not spamming that much when starting multiplayer ![изображение](https://user-images.githubusercontent.com/64935439/256280908-881a0506-3361-4f24-8ab6-e15bc4a3e4e9.png)
> > > 
> > > 
> > > Oh also i guess its spamming only when im setting Beatrun_HUDHidden 2 convar and its start spamming like in this picture down here ![изображение](https://user-images.githubusercontent.com/64935439/255695201-1af82ff4-b59e-47f4-bb9a-4ccc922a183a.png)
> > 
> > 
> > this is really odd since all of my addons are disabled and its just says theres an error somewhere
> 
> note: i just deleted all of my addons and deleted all of its cache, the error is still there somehow

And i can note that it only happens on first launch multiplayer, when disconnecting through menu and launching multiplayer again the lua error just dissapears which is really odd.

**Comment by RedyRT** [comment]
> Can you try this on latest commit? If it still persist, I suspect an addon conflict, maybe some HUD addon

What about if i will suggest you a fix, just add in the checkpoints.lua to the 248 line this code:

w = w or 0

The lua error will dissapear then. What do you think?

**Comment by RedyRT** [comment]
What about if i will suggest you a fix? Just add in the checkpoints.lua line 248 and 269

This code: w = w or 0

It should be like that 
![изображение](https://github.com/JonnyBro/beatrun/assets/64935439/6f1997f1-9ca7-4d2d-91b3-b8c1cde0c15d)
What do you think about it?

**Comment by JonnyBro** [comment]
I'll check that after work, thanks!

**Comment by RedyRT** [comment]
i also dont know should be this added into 263 line this code, cuz i didnt experienced lua error in this line

**Comment by JonnyBro** [comment]
You can make a pull request with those changes to be a contributor if you want. Or I can do it myself

> What about if i will suggest you a fix? Just add in the checkpoints.lua line 248 and 269
> 
> This code: w = w or 0
> 
> All what it does its just code checks the variable w for a value and assigns it the value 0 if it is missing
> 
> It should be like that ![изображение](https://user-images.githubusercontent.com/64935439/256395978-6f1997f1-9ca7-4d2d-91b3-b8c1cde0c15d.png) What do you think about it?
> 
> When i did these changes the lua spamming on Beatrun_HUDHidden convar and on both modes 0, 1, 2 just stopped

**Comment by JonnyBro** [comment]
And also can you try disabling Dynamic HUD and setting `Beatrun_HUDHidden 2`?
Without ur fix of course

**Comment by RedyRT** [comment]
> And also can you try disabling Dynamic HUD and setting `Beatrun_HUDHidden 2`? Without ur fix of course

I tried with all modes, like if i will set Beatrun_HUDHidden 2 it will lua spam as hell, but with Beatrun_HUDHidden 1 it just giving 1 lua error and nothing else

**Comment by JonnyBro** [comment]
This is really strange, I don't have that error on any settings combination

**Comment by RedyRT** [comment]
> This is really strange, I don't have that error on any settings combination

Yeah, strange, all what i can try is just install fresh garry's mod and see if it will fix

**Comment by JonnyBro** [comment]
> > This is really strange, I don't have that error on any settings combination
> 
> Yeah, strange, all what i can try is just install fresh garry's mod and see if it will fix, before making those changes

Ur fix shouldn't break anything, so feel free to create a pull request, or let me know if you want me to just push them with your credits

**Comment by RedyRT** [comment]
> > > This is really strange, I don't have that error on any settings combination
> > 
> > 
> > Yeah, strange, all what i can try is just install fresh garry's mod and see if it will fix, before making those changes
> 
> Ur fix shouldn't break anything, so feel free to create a pull request, or let me know if you want me to just push them and credit you

yeah after fresh install it giving me same error, so i will do pull request

**Comment by JonnyBro** [comment]
Thanks for your contribution!
