### ISSUE TITLE
slide instead of roll

### ISSUE THREAD

**Issue by Wisbe** [JonnyBro/beatrun#41]
slide instead of roll

it happened by accident when you fell and rolled instead of rolling you slide
after that you can't move

i cannot upload video, sorry!

**Comment by Wisbe** [comment]
this is not addon conflict, i have only maps and P.M. addons installed

**Comment by JonnyBro** [comment]
Can't replicate, can you try recording a video without any addons except beatrun and vmaniprework?

**Comment by mightbeusual** [comment]
use sliding ability in workshop, somehow fixes it.

**Comment by SpidermanArda** [comment]
https://github.com/JonnyBro/beatrun/assets/142094115/cc663faf-532d-4024-a490-b805c95ee835
holding the shift + W button while about to hit the ground causes this. after that happens. you cant do anything. not even noclip so you'll need to type kill on the dev console
meanwhile only holding shift doesnt accurs the bug.
