### ISSUE TITLE
[Suggestion] Is it possible to remove casting shadow for firstperson playermodel?

### ISSUE THREAD

**Issue by RedyRT** [JonnyBro/beatrun#47]
**Is your feature request related to a problem? Please describe.**
Is it possible to remove casting shadow from firstperson playermodel? because playermodel covers the flashlight, so i literally cant use the flashlight normally

**Describe the solution you'd like**
Remove casting shadow from firstperson playermodel

![изображение](https://github.com/JonnyBro/beatrun/assets/64935439/582a03c9-e109-4531-9d4b-24ad018b3e7e)

**Comment by JonnyBro** [comment]
From our Discord server (#commands-list)

Flashlight's shadow fix (when you see ur own shadow):
Add to `/GarrysMod/garrysmod/cfg/autoexec.cfg`
This: `
r_flashlightdepthtexture 0
`
