### ISSUE TITLE
[Suggestion] Live Player Cam (they said i'm a fucking seal 😒)

### ISSUE THREAD

**Issue by rotntake** [JonnyBro/beatrun#49]
**Is your feature request related to a problem? Please describe.**
there is a "live player cam" a camera of the player with a "sad" seal image on the top left
it makes me frustrated cuz this bitch depicting me as a seal 😡😡😡

**Describe the solution you'd like**
pls remove it

**Describe alternatives you've considered**
there are no alternatives, i cannot ignore this seal....

**Additional context**
image of da bitch sealy:
https://i.imgur.com/89Obzuf.png

**Comment by rotntake** [comment]
- [ ]

**Comment by JonnyBro** [comment]
You have conflicting with beatrun addons and you closed the warning
