### ISSUE TITLE
Is This Version or Modded version have backdoor , ip grabbing or malware ?

### ISSUE THREAD

**Issue by Vicalistic** [JonnyBro/beatrun#5]
is this beatrun version doesn't have malware , ip grabbing or backdoors ?
( when i heard **datae** do that stuff. its scares me cuz i dont want let my lil'bro download his version)
(my lil'bro want it so much and im afraid this beatrun have backdoor installed)

**Comment by jeffthekillerz** [comment]
this version is fully clear of any malware.

**Comment by JonnyBro** [comment]
No, my fork or @jeffthekillerz's version doesn't contain anything like that because we are cool B) (not like datae)

**Comment by Vicalistic** [comment]
Whats with **(Delete or disable VManip (Base) that downloaded from Workshop!)** ? Is it going track the modded beatrun ?

**Comment by jeffthekillerz** [comment]
no, it's just an older version. vmaniprework in this repo is up-to-date as it was acquired from the official beatrun discord server and it was modified by us to work with beatrun well.

**Comment by Shibu1nu** [comment]
wanted to ask but didn't want to make a whole "issue" thing (because it really isn't). is there a reason that windows defender flags the downloaded ZIP as being/having a Trojan?

**Comment by JonnyBro** [comment]
It's a false positive, ignore it. I think it doesn't likes the included .exe (Anims installer). Anims installer's source is included with the download, I just complied it so you don't have to
