### ISSUE TITLE
theres "newer animations" then the reanimated

### ISSUE THREAD

**Issue by ColoredGhost** [JonnyBro/beatrun#50]
the reanimated animatations got "re-reanimated", like in this one https://www.youtube.com/watch?v=hYIQGAs-l30&list=PLbShRwiQ1jUtSVprgbHnJKCvSpoaG_-Ch&index=6

i can see a resemblance to ME:C but not alot, idk if you guys have access to the beatrun files

**Comment by JonnyBro** [comment]
You can install different anims with this file [here](https://github.com/JonnyBro/beatrun/blob/master/beatrun/BeatrunAnimInstaller.exe), there is no more different animations

**Comment by mightbeusual** [comment]
outdated anims
