### ISSUE TITLE
[Bug] Landing on back causes random sliding at certain speeds (can sometimes softlock)

### ISSUE THREAD

**Issue by randomperson189** [JonnyBro/beatrun#51]
**Describe the bug**
When you land on your back (jump and right click) sometimes you'll randomly slide for a split second for no reason when you hit the ground at a certain speed. Sometimes when doing backwards get up animation, the slide causes you to softlock, unable to move

This issue doesn't occur when you have a weapon equipped so it should be an easy fix

**To Reproduce**
1. Run, jump, and then right click
2. Land on your back
3. See that you slide
4. Do the same but with a weapon equipped
5. See that you don't slide

**Expected behavior**
I should land on my back and not randomly slide for no reason, having a weapon equipped never causes this issue

**Screenshots/Videos**

https://github.com/JonnyBro/beatrun/assets/32617562/95e3f8bf-16db-4804-a2c3-00cce8edc003

https://github.com/JonnyBro/beatrun/assets/32617562/1a02c9a4-595c-4cfe-b92f-c2411acb65ec

**Additional information:**
 - Game Version: x64
- Game Type: Singleplayer

**Comment by mightbeusual** [comment]
i had this problem whenever i use arccw weapons. it's also better to use main version of the game, since x64 may cause issues with beatrun sometimes

**Comment by JonnyBro** [comment]
Can you try disabling each addon one by one and see what does this. I recently found out that [this](https://steamcommunity.com/sharedfiles/filedetails/?id=2052642961) addon can cause simillar problem, disable or uninstall if you have that

**Comment by IdiotBrazil** [comment]
> Can you try disabling each addon one by one and see what does this. Also, I recently found out that [this](https://steamcommunity.com/sharedfiles/filedetails/?id=2052642961) addon can cause simillar problem, disable or uninstall if you have that

Jonnybro I found out that [the ArcCW base ](https://steamcommunity.com/workshop/filedetails/?id=2131057232) does the same thing.
