### ISSUE TITLE
[Bug] <Add a title here!>

### ISSUE THREAD

**Issue by SpidermanArda** [JonnyBro/beatrun#53]
**Describe the bug**
A bug occurs whenever i try to do backwards recovery 
**To Reproduce**
1. Go to https://steamcommunity.com/sharedfiles/filedetails/?id=2876266251
2. do the spin while in the air (jump + rmb)
3. Press S
4. The bug occurs

**Expected behavior**
it sould do the backwards recovery normally instead of sliding.
**Screenshots/Videos**
(https://github.com/JonnyBro/beatrun/assets/142094115/5ce2ece6-4a0c-45e8-8791-808dacd59394)

**Additional information:**
 - Game Version: non-beta
- Game Type: Singleplayer

**Additional context**
doing this in multiplayer doesnt seems to make the bug occur for me

**Comment by JonnyBro** [comment]
Thats an addon conflict, you should try to disable each addon individually and see if it help. Let me know of the addon that does that when you find it!
