### ISSUE TITLE
[Bug] can't roll using left ctrl after zipline use

### ISSUE THREAD

**Issue by CootieDwagon** [JonnyBro/beatrun#55]
Describe the bug:
when you press left ctrl to get off a zipline, it won't let you use left ctrl to roll when you land on the ground.
you instead need to use left shift.

To Reproduce
1.) use a zipline
2.) press left ctrl key to get off the zipline
3.) while falling to the ground, press left ctrl key to try and roll.
4.) you won't be able to roll. only way is to press left shift

Expected behavior:
I expected to be able to roll using the same key as getting off a zip;line, it feels more natual to do so instead of trying to adjust
for pressing left shift key

Additional information::
 singleplayer. x64 chromium branch

**Comment by JonnyBro** [comment]
very strange error, don't know why it occurs

**Comment by IlikeFreerunning** [comment]
yes I'm currently making a course and it has a big zipline drop and I've been wondering what's happening thanks for bringing attention to this

**Comment by JonnyBro** [comment]
I'll close this issue because it's related to https://github.com/JonnyBro/beatrun/issues/124
