### ISSUE TITLE
[Bug] <Improper "diving" operation>

### ISSUE THREAD

**Issue by TBonist1** [JonnyBro/beatrun#59]
**Describe the bug**
If you use a "dive" to climb somewhere, then within a second, instead of a "dive," you'll fall.

**To Reproduce**
1. go to a place where you can go diving.
2. Climb in by "diving"
3. Now try using the dive immediately after climbing in
4. Instead of diving, you'll turn around and fall on your back

**Expected behavior**
I guess I'll just have to do the following diving.

**Additional information:**
 - Game Version: Chromium garry's mod x64

https://github.com/JonnyBro/beatrun/assets/143571637/49a4e213-6309-4ded-aa29-22aaaf932024

- Game Type: singleplayer

**Additional context**
I translated everything with the help of a translator, but I think with the video I explained everything clearly

**Comment by TBonist1** [comment]
And I'm pretty sure I pressed all the buttons correctly.

**Comment by JonnyBro** [comment]
I don't think that is a bug, more likely a cooldown

**Comment by TBonist1** [comment]
> I don't think that is a bug, more likely a cooldown
@JonnyBro
But there is no cooldown if I don't climb anywhere. Then it would be logical to add such a cooldown if you don't climb anywhere, just after any use of "diving". Or add a separate tab in the beatrun config where you can turn off this cooldown. It's very annoying.

**Comment by JonnyBro** [comment]
Only if I know how, this shit code is driving me crazy

**Comment by TBonist1** [comment]
Why did you close it? The bug is still there.
