### ISSUE TITLE
[Suggestion] color filter and mirrors

### ISSUE THREAD

**Issue by honey-badger3** [JonnyBro/beatrun#61]
can we get disable option for shit filter in beatrun/gamemode/cl/HUD.lua:418
and second is it possible to bring back func_reflective_glass or is it cause more bugs?
beatrun/gamemode/sh/Misc:143

**Comment by JonnyBro** [comment]
try and see

**Comment by JonnyBro** [comment]
![image](https://github.com/JonnyBro/beatrun/assets/48434875/4b724609-59bd-49a2-9da1-4d7e85d234e7)
And you can do this
