### ISSUE TITLE
[Bug] Some Player Models show up as errors in firstperson.

### ISSUE THREAD

**Issue by Stannowsky** [JonnyBro/beatrun#62]
**Describe the bug**
Some playermodels (ex: https://steamcommunity.com/sharedfiles/filedetails/?id=744357881) show up as errors

**How To Reproduce**
1. Go to '(https://steamcommunity.com/sharedfiles/filedetails/?id=744357881)'
2. Click on 'Subscribe'
3. Open game
4. Apply Playermodel
5. See error

**Expected behavior**
Looking down to see legs/body shows an error

**Screenshot**
https://github.com/JonnyBro/beatrun/assets/141931716/1e69bfad-e07b-40f0-801f-09dc081e5980

**Additional information:**
 - Game Version: x64
- Game Type: SinglePlayer

**Additional context**
Pretty Much deafult settings, nothing changed in beatruns config.
Mod that may cause issue: https://steamcommunity.com/sharedfiles/filedetails/?id=2247755443

**Comment by JonnyBro** [comment]
pretty funny, i'll take a look

**Comment by JonnyBro** [comment]
fixed from https://github.com/JonnyBro/beatrun/commit/bf304985f3f417daa3dcfe9bf2d546af9ee164a8

**Comment by JonnyBro** [comment]
sorry that took a month lol, was busy with work
