### ISSUE TITLE
[Bug] SmartSnap Addon breaks the roll

### ISSUE THREAD

**Issue by Trotacielos** [JonnyBro/beatrun#64]
Title is self explanatory, the addon SmartSnap ( https://steamcommunity.com/sharedfiles/filedetails/?id=104815552 ) makes the roll not work by instead turning it into a slide that pulls the first person camera a few inches away from the body, then once said slide is finished the player will get stuck on a standing position unable to move or do anything other than look around/down at their body, this is fixed as soon as the player dies and respawns (only tested so far with kill bind). Using the R key to respawn also gets disabled while on that state.

**Comment by JonnyBro** [comment]
thanks
