### ISSUE TITLE
[Bug] i can see my own body while using my flashlight, this happends with most player models but not all.

### ISSUE THREAD

**Issue by Maicouh** [JonnyBro/beatrun#67]
**Describe the bug**
a bug where I can see my own body when I shouldn't.

**Screenshots/Videos**
![20230904155248_1](https://github.com/JonnyBro/beatrun/assets/144028699/8e78a7ce-67fa-42a7-96d5-a15e4ae9f7a1)

**Additional information:**
 - Game Version: chromium, x64
- Game Type: singleplayer

**Additional context**
I don't have any lighting mods other than player models, this happens on all maps. When I look almost straight forward it also dims the flashlight or doesn't have any light from the flashlight.

**Comment by CootieDwagon** [comment]
> 

ahh yeah that. someone even said the normal beatrun has this issue. to try and fix this, try typing this into console (or put this into an auto.exc file)

r_flashlightdepthtexture 0

**Comment by JonnyBro** [comment]
This is a known issue and it won't be resolved.
You can use this console command to "fix" this: `r_flashlightdepthtexture 0`
