### ISSUE TITLE
[Bug] Old Modern Warfare sweps ADS

### ISSUE THREAD

**Issue by IdiotBrazil** [JonnyBro/beatrun#68]
**Describe the bug**
When aiming down sides without any scopes on old modern warfare sweps, depending on the place you look weapon starts moving to left or right.

To Reproduce
1. Download 'https://steamcommunity.com/sharedfiles/filedetails/?id=2873556895'
2. Turn left and right while aiming with the guns

**Screenshots/Videos**
'https://github.com/JonnyBro/beatrun/assets/144269963/61934c6c-d9a9-420c-b39d-df88c50be89c' (I had to lower the quality and time to make it less than 10mb)

**Additional information:**
 - Game Version: [chromium, x64]
- Game Type: [both singleplayer and multiplayer]

**Additional context**
This bug used to happen on the original modern warfare sweps base (on the beatrun demo) before it got changes but after that it doesnt happen,

**Comment by JonnyBro** [comment]
First, this is a MW Base unofficial addon + Legacy (don't updated and will not updated for latest MW Base, check addon's description)
Second, Thats not my problem
Third, I will not fix that

**Comment by IdiotBrazil** [comment]
> First, this is a MW Base unofficial addon + Legacy (don't updated and will not updated for latest MW Base, check addon's description) Second, Thats not my problem Third, I will not fix that

I do know its the unofficial legacy base that isnt getting updated, i just wanted to point the bug that happens when you use it with beatrun
