### ISSUE TITLE
[Bug] MWBASE RELATED CRASH (SOLVED... SORRY!)

### ISSUE THREAD

**Issue by dataesucsdeek** [JonnyBro/beatrun#69]
heres how to replicate (on my end)
>grab any mw base gun
>edit gun
>go out of edit and press right click to aim
>game freezes. then closes
anything you could look into??

**Comment by dataesucsdeek** [comment]
i know the beatrun thing says tfabase is a conflicting addon but tfa has 0 issues when i used it today.
but mw base seems to crash instantly on right clicking.
also u cant backdive with any gun when u walk backwards
also the mw base guns crash seems to happen at random. bc it first happened RANDOMLY when i was shooting and aiming with mw base guns. now it happened the instant. i pressed right click.

**Comment by dataesucsdeek** [comment]
though this is completely unnecessairy and stupid to ask. i know one of you will still mention it.
the gun causing the crashes. twice. (bc i didnt use any other gun) 
was: https://steamcommunity.com/sharedfiles/filedetails/?id=2982791107

**Comment by dataesucsdeek** [comment]
note, the crash didnt happen before with the same exact gun.

**Comment by dataesucsdeek** [comment]
my guess is: the mw base gun dissapearing when rolling feature you added probably causes some lua errors leading to a crash. or something similar. try removing this feature untill you find a better solution. just my gut telling me its mw base shitting itself.

**Comment by dataesucsdeek** [comment]
also a 2nd bug i forgot to mention.
when holding the beatrun swep (the hands thing "unarmed")
holding s. pressing space then pressing rightclick doesnt do the right falling backwards sequence. and getting up just shakes ur camera up and it looks like uncrouching

**Comment by dataesucsdeek** [comment]
side note 2:
i found this crash log thing. (its useless)

>Executable: F:\SteamLibrary\steamapps\common\GarrysMod\bin\win64\gmod.exe
>
>-Lua Stack Traces-
>==================
> Client
>    Lua Interface = NULL
>
>  Server
>   *Not in Lua call OR Lua has panicked*

>  MenuSystem
>    *Not in Lua call OR Lua has panicked*

**Comment by dataesucsdeek** [comment]
sorry for the spam. trynna give as much info as possible.

**Comment by dataesucsdeek** [comment]
error code related to being unable to fall backwards
>[beatrun] addons/beatrun/gamemodes/beatrun/gamemode/sh/quickturn.lua:59: attempt to index global 'ply' (a nil value)
  1. DoJumpTurnStand - addons/beatrun/gamemodes/beatrun/gamemode/sh/quickturn.lua:59
   2. unknown - LuaCmd:1

**Comment by dataesucsdeek** [comment]
ALL OF THIS IS IRRELEVANT NOW EXCEPT THE COMMENT ABOVE WITH THE ERROR CODE.
I FIXED THE CRASHES BY DISABLING TFA BASE (SADLY I HAD SOME GOOD SWEPS ON THAT)

**Comment by dataesucsdeek** [comment]
interesting sidenote: tfa-base only crashes if you use mw base with it...
for me thats how it went atleast...

**Comment by dataesucsdeek** [comment]
[beatrun] addons/beatrun/gamemodes/beatrun/gamemode/sh/sh_freerunsysall.lua:31: attempt to call method 'SendLua' (a nil value)
  1. Hardland - addons/beatrun/gamemodes/beatrun/gamemode/sh/sh_freerunsysall.lua:31
   2. func - addons/beatrun/gamemodes/beatrun/gamemode/sh/sh_freerunsysall.lua:43
    3. unknown - lua/includes/extensions/net.lua:38 (x5)

**Comment by JonnyBro** [comment]
beatrun errors fixed in latest commit
