### ISSUE TITLE
[Bug] <Bug when falling on your back after a recent fix>

### ISSUE THREAD

**Issue by TBonist1** [JonnyBro/beatrun#70]
**Describe the bug**

When you fall on your back, you don't get up until you jump up

**To Reproduce**
1) jump and press the right mouse button
2) When you fall on your back try to get up.
3) Fail, you will remain in the lying animation and will not be able to turn your head more than 90 degrees.

**Additional context**
The bug appeared recently when I downloaded beatrun after 241 update (or whatever it is, it says 241 commit) And played until the new updates came out, which is the same on 241. Maybe it appeared a bit earlier than 241 update.

**Comment by JonnyBro** [comment]
should be fixed in latest commit
