### ISSUE TITLE
[Suggestion] a fix for tfa compatibility.

### ISSUE THREAD

**Issue by dataesucsdeek** [JonnyBro/beatrun#71]
theres many good tfa sweps and is there any way to stop tfa from crashing gmod with beatrun in any way.
i hope to see a fix soon cause theres some REALLY nice tfa sweps that i sadly had to remove.

**Comment by JonnyBro** [comment]
I was thinking about removing TFA from incompatible, because I don't have any issues running any TFA weapon with beatrun

**Comment by dataesucsdeek** [comment]
> I was thinking about removing TFA from incompatible, because I don't have any issues running any TFA weapon with beatrun

sorry for the lat late reply but unsubbing tfa for me fixed some crashes...

**Comment by JonnyBro** [comment]
¯\\_(ツ)_/¯

**Comment by Maicouh** [comment]
This definitely would be nice

**Comment by JonnyBro** [comment]
removed tfa from addonwarning, dunno why it's crashing tho
