### ISSUE TITLE
Maybe a Video Tutorial?

### ISSUE THREAD

**Issue by TinnyTin11** [JonnyBro/beatrun#72]
For some reason I can't install the beat run mod, I've tried both methods (Manual and Automatic) so I think having a video tutorial would be nice to have because video tutorials are much easier to follow than text ones (imo)

**Comment by dataesucsdeek** [comment]
readthe installation steps again. and tedo them.
idk why you need a video if everyone else including me got beatrun running instantly.
just copy the correct files into the correct directory. hows that hard?

**Comment by zarkerthegamerv2** [comment]
i can't figure it out i have tried for the last 2 hours please help

**Comment by JonnyBro** [comment]
I'll make a video tutorials later
