### ISSUE TITLE
how tf do i use this?

### ISSUE THREAD

**Issue by zarkerthegamerv2** [JonnyBro/beatrun#73]
for the last 2 hours i have been trying to figure it out help me please

**Comment by CootieDwagon** [comment]
> for the last 2 hours i have been trying to figure it out help me please

you know when you download the repository from the link it says? it should give you the "beatrun-master.zip" file. im assuming you have that right? if so then you do this

you extract it with either 7zip or winrar.

after you extract it, go through the folders until you enter a folder which contains all of these (will use "quotes" to mark which ones are a "folder"

.gitignore
.glualint
LICENCE
README
".github"
"beatrun"
"BeatrunAminInstaller"
"lua"

take the "beatrun" folder and copy it (or drag it) to your



Steam\steamapps\common\GarrysMod\garrysmod\addons

drag it into here (or copy and paste it into here)

you are done. when you load up gmod you should be able to select beatrun as a gamemode from the bottom right menu on the main menu (you will be on Sandbox by default)

**Comment by JonnyBro** [comment]
I'll make a video tutorials later

**Comment by zarkerthegamerv2** [comment]
its working

**Comment by zarkerthegamerv2** [comment]
thanks btw
