### ISSUE TITLE
[Suggestion] Can you add the ability to fall backwards with any weapons as an option in the menus

### ISSUE THREAD

**Issue by Daota1** [JonnyBro/beatrun#76]
I really liked when we could fall backwards and shoot people with guns and I was a bit dissapointed when the feature was made exclusive to runner hands, could you add the feature back please, id be grateful. also great work on the addon

**Comment by Poggas1256** [comment]
um, this is a thing, jump backwards in the air and press right click and it makes you fall backward just like with runner's hands

**Comment by Daota1** [comment]
it doesnt work for me though, i can only fall backwards with the runner's hands and I don't know why

**Comment by JonnyBro** [comment]
> it doesnt work for me though, i can only fall backwards with the runner's hands and I don't know why

Because I made it so

**Comment by JonnyBro** [comment]
How are you gonna use scopes while jumping?

**Comment by ContentStatic** [comment]
> How are you gonna use scopes while jumping?

that's why they said "add it as a option in the menu"

**Comment by JonnyBro** [comment]
Question still remains

> > How are you gonna use scopes while jumping?
> 
> that's why they said "add it as a option in the menu"

**Comment by ContentStatic** [comment]
just don't?

> Question still remains
> 
> > > How are you gonna use scopes while jumping?
> > 
> > 
> > that's why they said "add it as a option in the menu"

**Comment by ContentStatic** [comment]
i mean if you have it on you're gonna be fully aware you can't use your optics while jumping right

> Question still remains
> 
> > > How are you gonna use scopes while jumping?
> > 
> > 
> > that's why they said "add it as a option in the menu"

**Comment by num3raI** [comment]
You could have it for the middle mouse button so you can still use optics while jumping.

**Comment by biirdiest** [comment]
i also really liked this feature, i thought i was having issues on my end

**Comment by JonnyBro** [comment]
Fine, I'll add this option today

**Comment by JonnyBro** [comment]
Added in https://github.com/JonnyBro/beatrun/commit/f3dbf0b2de7d0f0d896d264c8f7948a73d55d46b

**Comment by biirdiest** [comment]
thanks man
