### ISSUE TITLE
first person ladder bug

### ISSUE THREAD

**Issue by CootieDwagon** [JonnyBro/beatrun#77]
EDIT: bug only seems to happen on this map https://steamcommunity.com/sharedfiles/filedetails/?id=113136606

perhaps the ladders were made wrong or something. or it might just be those pipes on this map

while on a none Beatrun ladder in first person and moving up or down, your body will bug out when you look down, also noticeable sometimes without looking down

was on x86 chromium branch

1. Go on a none beatrun ladder or pipe (pipe that acts like a HL2 ladder works too)
2. look down
3. you will see your body being weird
4. sometimes it can be seen without looking down

Screenshots/Videos
![Body_bug](https://github.com/JonnyBro/beatrun/assets/84007270/0c54da36-f4ef-401c-ab0b-62ec5a0a2cd3)

**Comment by CootieDwagon** [comment]
forgot tot add, this is in first person when doing this, and it uses the most recent GitHib version that was relased as of the posting of this bug report

**Comment by JonnyBro** [comment]
will not fix that
