### ISSUE TITLE
[Bug] Ladders not spawning/working properly after loading a save

### ISSUE THREAD

**Issue by Canpake59** [JonnyBro/beatrun#78]
**Describe the bug**
Placed beatrun ladders in build mode around a map that were fully functional. Created a save of the map, so my progress wasn't lost. Loaded the save the next day and all my ladders were either stuck in the wall but still worked, or stuck in the wall and did NOT work.

**To Reproduce**
1. Create ladders
2. Create a save
3. Load the save
4. See broken ladders

**Expected behavior**
Ladders should be in the same position and function the same way as they did before creating the save

**Screenshots/Videos**
What the ladder should look like:
![20230916163909_1](https://github.com/JonnyBro/beatrun/assets/30377331/3ffd3db7-dfdd-4276-9f78-4d8127542322)
What it DOES look like after loading save:
![20230916163749_1](https://github.com/JonnyBro/beatrun/assets/30377331/1bcc365f-aa04-43c9-8907-b4c0e13801f2)
Video of the ladder functioning, but obviously visually not in the correct place:

https://github.com/JonnyBro/beatrun/assets/30377331/cc46fc83-90da-46df-a7db-e6698cf46230

**Additional information:**
 - Game Version: [x86-64]
- Game Type: single player

**Additional context**
Beatrun config left unchanged.

**Comment by JonnyBro** [comment]
Did you saved the course with Beatrun's command or in-game save?

**Comment by Canpake59** [comment]
I used the in game save because i wasn't making a "course" that was being timed. I just wanted to put ladders in the world for when I play in sandbox with the beatrun game mode.

**Comment by JonnyBro** [comment]
You should save your progress as course. When you need to edit your "unfinished" course, you can start it, open build mode and edit what you need, then save again. In-game saves are not supported
