### ISSUE TITLE
Sliding Broken and grappling not working

### ISSUE THREAD

**Issue by AtaKanK4467** [JonnyBro/beatrun#8]
I dont know why but when i slide the character does not get up and just continues sliding, the only fix is to reset your character by pressing r while unarmed or type kill on console. I do not know why this happens. Also the grappling hook doesnt work, i press space mid air and nothing happens.

**Comment by JonnyBro** [comment]
I'm aware about this problem, will push update soon, will hope it fixes everything

**Comment by JonnyBro** [comment]
Fixed with latest update
