### ISSUE TITLE
[Bug] sliding while laying on back

### ISSUE THREAD

**Issue by CootieDwagon** [JonnyBro/beatrun#80]
as of the most recent update that happened about 19h ago according to what im seeing here. when you are running then jump and flop onto your back, instead of flopping on your back, you will land on your back and instantly slide which forces you to stand back up after sliding

1. start running forward
2. jump and press right click while running
3. you will flop onto your back and then instantly enter a slide the moment you land on your back, borking the animation

Expected behavior
I expected to flop onto my back and stay there like i used to in a previous update

Additional information:
 - Game Version: chromium, x64]
- Game Type: singleplayer

**Comment by JonnyBro** [comment]
That's intentional (maybe? not sure? don't have time now to research?)

**Comment by CootieDwagon** [comment]
> That's intentional (maybe? not sure? don't have time now to research?)

feel free to close this topic again, but i did want to say, if we are looking at the normal mirrors edge game. then anytime you flop onto your back (even from running forward then doing a back flop) it is 100% supposed to stop ALL momentum and keep you flopped onto your back until you press W or S. it is NOT supposed to go from a back flop right into a slide animation the moment you flop onto your back after running forward. with it doing that it causes the animations to become "stretchy" and weird for a few moments.

if we were to look at Dataes version of beatrun, that one has it to where if you flop onto your back, it stops all momentum and keeps you in the back flop animation until you press S or W just like how the normal mirrors edge game does it.

ive tested this plenty of times in the normal mirrors edge game, and doing a back flop 100% of the time always stops all momentum and does NOT put you into a "slide" animation if you were running and then back flopped.

if you do decide to not change this, it wouldn't be the end of the world. but just know that there will be "stretchy" body texture for a few moments once the "slide" triggers :)
