### ISSUE TITLE
fix clipping on body just a little bit pls

### ISSUE THREAD

**Issue by IlikeFreerunning** [JonnyBro/beatrun#81]
fix clipping on body just a little bit pls

**Comment by JonnyBro** [comment]
what clipping, where. I don't read minds

**Comment by IlikeFreerunning** [comment]
i mean when doing parkour your camera clips into your body and it kinda ruins the experience for me. sorry for not being specific

**Comment by JonnyBro** [comment]
I don't play beatrun myself that much, can you attach some video examples?

**Comment by IlikeFreerunning** [comment]
sure let me figure out how to gimme one sec

**Comment by JonnyBro** [comment]
You can join our Discord and post your video there

**Comment by JonnyBro** [comment]
missclick

**Comment by IlikeFreerunning** [comment]
hi whats the server name?

**Comment by JonnyBro** [comment]
https://discord.gg/93Psubbgsg

**Comment by IlikeFreerunning** [comment]
it said invite invalid

**Comment by JonnyBro** [comment]
it is valid

**Comment by IlikeFreerunning** [comment]
can u tell me name of discord?

**Comment by JonnyBro** [comment]
Just upload your video somewhere already, you can use YouTube or any file sharing service.

**Comment by IlikeFreerunning** [comment]
can u please just send me another invite link or something on discord?

**Comment by JonnyBro** [comment]
https://discord.com/invite/93Psubbgsg
