### ISSUE TITLE
ловля и удержание уступов

### ISSUE THREAD

**Issue by IlikeFreerunning** [JonnyBro/beatrun#82]
Можете ли вы добавить способность цепляться за уступы вместо того, чтобы перепрыгивать через них? Я хочу этого, потому что я делаю stealth видео.

**Comment by demiantmb** [comment]
> Можете ли вы добавить способность цепляться за уступы вместо того, чтобы перепрыгивать через них? Я хочу этого, потому что я делаю stealth видео.

W отпусти когда карабкатся начал

**Comment by IlikeFreerunning** [comment]
спасибо, но как я могу это сделать, когда я стою на выступе
