### ISSUE TITLE
[Bug] lower body blocks flashlight

### ISSUE THREAD

**Issue by biirdiest** [JonnyBro/beatrun#83]
the flashlight starts from behind the lower body, blocking most of the light and looking really weird. im not using any addons that modify shadows either
![image_2023-09-30_171353271](https://github.com/JonnyBro/beatrun/assets/145905168/8b01dd75-96d6-4fb5-a5d5-9c4eca3b9db1)

i think the lower body shouldnt be able to cast any shadows in any way since it also appears alongside the normal player shadow if you have firstperson shadows enabled

**Comment by biirdiest** [comment]
if it actually is a option or command i have enabled please let me know

**Comment by JonnyBro** [comment]
Add to `/GarrysMod/garrysmod/cfg/autoexec.cfg` and then run in console too:
`
r_flashlightdepthtexture 0
`

**Comment by biirdiest** [comment]
thx
