### ISSUE TITLE
[Bug] Black screen

### ISSUE THREAD

**Issue by Gnaw9012** [JonnyBro/beatrun#85]
When I start the game and enter a map a strange black screen appears on the entire screen. happens on any map

Additional information:
 - Game Version:chromium, x86-64
- Game Type::singleplayer

**Comment by JonnyBro** [comment]
did you removed old beatrun before updating?
remove everything old (`beatrun` and `vmaniprework` folder if you have them) and install latest one from [here](https://github.com/JonnyBro/beatrun?tab=readme-ov-file#prefered-installation-automatic--windows-only)

**Comment by Gnaw9012** [comment]
yes i removed

**Comment by JonnyBro** [comment]
there was a black screen lua in "license" releases, we dont have it here, so I don't have why you have that error. Try joining our Discord server and asking for help there

**Comment by Gnaw9012** [comment]
how to enter the server, i dont know lol

**Comment by JonnyBro** [comment]
https://beatrun.ru, there is a button for our discord and courses database
