### ISSUE TITLE
[Suggestion] Ghosts for Course Mode (Tracked player)

### ISSUE THREAD

**Issue by Robo798814** [JonnyBro/beatrun#86]
My suggestion is to add a feature for courses where the mod will record the player's position then show it in the form of a ghost when the player restarts the course.

To prevent more than two ghosts from spawning (Unless in multiplayer or in other scenarios), the mod will delete the last ghost and use newly recorded data from the player's movement. This feature should be disabled by default.

Below is an image of what I meant.
![image](https://github.com/JonnyBro/beatrun/assets/29616390/d912702f-6251-4a0a-ac14-7c77b939a9ff)

**Comment by SleepyCatOfficial** [comment]
Would be cool! But idk if you could do it tho

**Comment by UnderSet** [comment]
> Would be cool! But idk if you could do it tho

Very likely possible, there's some commented out code for recording replays in [Checkpoints.lua](https://github.com/JonnyBro/beatrun/blob/9657de48fe40dbe480645c9a4c99a9e78610035a/beatrun/gamemodes/beatrun/gamemode/sh/Checkpoints.lua#L311) and also the entire [Replay.lua](https://github.com/JonnyBro/beatrun/blob/main/beatrun/gamemodes/beatrun/gamemode/sh/off/Replay.lua) file, which means theoretically you can make a ghost follow the recorded replay. I don't know how to make it work though, and I have no idea how to even draw a ghost in the first place, and there's no code about calling the replay ***playing*** function, so I don't know how to use that.

**Comment by JonnyBro** [comment]
> > Would be cool! But idk if you could do it tho
> 
> Very likely possible, there's some commented out code for recording replays in [Checkpoints.lua](https://github.com/JonnyBro/beatrun/blob/9657de48fe40dbe480645c9a4c99a9e78610035a/beatrun/gamemodes/beatrun/gamemode/sh/Checkpoints.lua#L311) and also the entire [Replay.lua](https://github.com/JonnyBro/beatrun/blob/main/beatrun/gamemodes/beatrun/gamemode/sh/off/Replay.lua?rgh-link-date=2023-11-04T03%3A02%3A22Z) file, which means theoretically you can make a ghost follow the recorded replay. I don't know how to make it work though, and I have no idea how to even draw a ghost in the first place, and there's no code about calling the replay _**playing**_ function, so I don't know how to use that.

This Replay.lua file plays replays of your courses when you finished but as I remember it's not implemented fully, thats why I commented all the code (it also was making some random errors)

**Comment by UnderSet** [comment]
> This Replay.lua file plays replays of your courses when you finished but as I remember it's not implemented fully, thats why I commented all the code (it also was making some random errors)

Makes sense, probably partly because it's (presumably) only meant to be used in the lost training map (`br_training`) as that's apparently where the replay code gets, you know, **actually used?**.

I also found out how to start a replay (`ReplayPlay()`), though I can't for the life of me understand how to use that function outside of the training map.

I'd like to try and finish this issue sometime, but that'll have to wait - I have tests to do this week, and besides I gotta get the replays themselves to work right first to get this issue to progress anyway.

This is getting a "little" offtopic from the main issue though.

**Comment by JonnyBro** [comment]
@UnderSet 
I'll close this issue and will check on your repo sometime. Fell free to ping me in our Discord server for everything related!
