### ISSUE TITLE
[4 Suggestions] Climbable pipes, moving around the edges and walk in small space, Stand on swingbar

### ISSUE THREAD

**Issue by Didtruo** [JonnyBro/beatrun#89]
Climbable pipes would be cool to see, it would be more like a reskin of a ladder but with different animations and would allow to move much quicker around pipes in environment (jump from one to another).

about moving around the edges i dont know if its possible because there would be need to make a script that detects if theres enough space if player can go around it.
Moving around the edges video:

https://github.com/JonnyBro/beatrun/assets/146891537/eaaa9bc2-0338-4bfd-9231-cdd1bb20d3eb

By walking in small space i mean outlast-like and mirrors edge-like where you slow down to get among 2 props or just wall,

Image explaining what i mean:
![1655569578](https://github.com/JonnyBro/beatrun/assets/146891537/edecd450-2f4c-442e-828c-db11b3ca7545)

about standing on swingbar, it would be cool if that was possible, if player stop swinging he would be able to stand on it like in mirror's edge catalyst

**Comment by JonnyBro** [comment]
I don't think that I will do that
