### ISSUE TITLE
Still unable to slide/grapple/mantle and vault

### ISSUE THREAD

**Issue by BeckJack32** [JonnyBro/beatrun#9]
I reinstalled Beatrun to the newest version, not replacing any files completely from scratch and I did the same for Vmaniprework, I'm running on Chromium/64-bit version of Gmod on the map Catalyst Blockout, above 60 FPS, the most consistent way I have found to replicate this bug was my either coiling into a slide or kicking while sliding, as previously mentioned I followed the new instructions for the installation 1:1, I tried fiddling around with the new kick glitch settings also to no avail, if video proof or something alike is needed I will provide it if requested.

Edit: Forgot to mention that I uninstalled the Workshop version of Vmanip, so that isn't causing the issue

**Comment by JonnyBro** [comment]
Try latest release, should be good now (i hope)

**Comment by BeckJack32** [comment]
Yup, works perfectly
