### ISSUE TITLE
[Suggestion] Music

### ISSUE THREAD

**Issue by Robo798814** [JonnyBro/beatrun#90]
Both Freeplay and Course mode can feel dull at times without music being played in the background, whereas part of what made Mirror's Edge and Dying Light great were the music tracks. My suggestion is to add the ability for Beatrun to play music in the background, where the music will change depending on whether you're playing on Freeplay or Course mode. 

The default music, in my opinion, could could be tracks from Mirror's Edge, while I recommend to be able to be turned on or off by the discretion of the player.. Finally, I recommend that the music tracks are customizable, like Nombat.

**Comment by Didtruo** [comment]
i think its not so necessary to add it because theres mods like Nombat and Dynamic Music that exists, but it would be cool if the music had some detection of player in the air and add some effect of the music in it for instance 2 tracks plays at the same time, but when you are in air the other one plays until player lands.

**Comment by seacat17** [comment]
Just to clarify: I love this idea. The soundtrack that symbolizes your freedom when you're running would be like a new life to Beatrun after all that mess.

**Comment by Robo798814** [comment]
> i think its not so necessary to add it because theres mods like Nombat and Dynamic Music or just Spotify that exists, but it would be cool if the music had some detection of player in the air and add some effect of the music in it for instance 2 same tracks but 1 has some effect and is muted and plays at the same time, but when you are in air the other one plays until player lands.

While it's true that Nombat and Dynamic Music can work with Beatrun, the issue is that the music does not dynamically react to either what the player is doing or the status of the course. For example, when the course is completed, the music should abruptly stop and wait until the player reenters freeplay mode or retries the course. 

Nombat unfortunately doesn't do this, and it would also be nice if Beatrun played combat music too should the devs decide to add enemies as part of course mode (Which I hope, but that's a topic for another Suggestion thread).
