### ISSUE TITLE
buggy finishers

### ISSUE THREAD

**Issue by IlikeFreerunning** [JonnyBro/beatrun#91]
when i do a finisher on someone their body disappears

**Comment by CootieDwagon** [comment]
this happens even in the "offical" Beatrun version by datee. idk if this can be fixed

**Comment by IlikeFreerunning** [comment]
oohhhhh ty

**Comment by demiantmb** [comment]
disable keep corpses

**Comment by IlikeFreerunning** [comment]
OHHHHHHHHHHHHHHHHHHHH

**Comment by demiantmb** [comment]
comes with the downside of ragdoll mods not working unless they modify the .phy files, you can close the issue if you want
