### ISSUE TITLE
[Bug] Опечатка

### ISSUE THREAD

**Issue by AlshaKrut9523-2** [JonnyBro/beatrun#94]
**Describe the bug**
В Build Mode вместо "Удалить" написано "Удадлить" 🤓

**Screenshots/Videos**
![image](https://github.com/JonnyBro/beatrun/assets/73034968/daf7788a-0917-4109-b952-792578e6111d)

**Additional information:**
non-beta, singleplayer

**Comment by JonnyBro** [comment]
Спасибо, исправил в ласт коммите
