### ISSUE TITLE
[Bug] Clipping when turning fast

### ISSUE THREAD

**Issue by CootieDwagon** [JonnyBro/beatrun#95]
when you turn left or right too fast even when crouching, you see your weird clipping body

1. load up the beatrun gamemode
2. when you spawn in, turn left or right
3. you will see your body clipping

i expected to not see my body clipping

![bug](https://github.com/JonnyBro/beatrun/assets/84007270/8f1daf27-57d1-4a59-9f49-b0eaeef7578e)

 - Game Version: chromium, x64
- Game Type: singleplayer

in previous updates i was never able to see my clipping body when turning fast. it is only recently in these past updates that i can now start to see my clipping body when turning fast.

**Comment by JonnyBro** [comment]
thats just how beatrun works, there will be no fix for that
