### ISSUE TITLE
[Bug] is there a way to disable damage viewpunch and health regen?

### ISSUE THREAD

**Issue by Mikeyisthatboi** [JonnyBro/beatrun#96]
its really annoying when im fighting npcs and my view jerks upward when i get shot there a tweak for this?

**Comment by JonnyBro** [comment]
viewpunch: check the code
regen: https://github.com/JonnyBro/beatrun/blob/main/beatrun/gamemodes/beatrun/gamemode/sh/Damage.lua#L79
