### ISSUE TITLE
[Suggestion] Mirrors Edge Catalyst Animations?

### ISSUE THREAD

**Issue by CootieDwagon** [JonnyBro/beatrun#98]
would it be possible to add MEC animations for Beatrun? such as for the Safety roll, jump, slide and maybe running?

or do you only ever plan to have just 2 animation types. the "original animations" and "beatrun reanimated"?

just wondering

**Comment by mightbeusual** [comment]
only 2 animation types that we will focus on. 
unless anyone are willing enough to make their own beatrun MEC animations compatible for beatrun, then go ahead.

**Comment by IlikeFreerunning** [comment]
it would be super cool tho
